### ISSUE TITLE
No gcc for mcr.microsoft.com/azure-functions/python:2.0 image

### ISSUE THREAD

**Issue by xiacijie** [Azure/azure-functions-docker#100]
When it is executing pip install -r requirements.txt and comes to regex,
the error shows up.

`gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.6m -c regex_3/_regex.c -o build/temp.linux-x86_64-3.6/regex_3/_regex.o unable to execute 'gcc': No such file or directory error: command 'gcc' failed with exit status 1`

**My Docker file**
```
FROM mcr.microsoft.com/azure-functions/python:2.0

COPY . /home/site/wwwroot

RUN cd /home/site/wwwroot && \
    pip install -r requirements.txt && \
    export CLASSPATH=./nlp_package/corenlp/*

```
**requirements.txt**

```
numpy
scikit-learn
regex
tqdm
scipy
nltk
pexpect==4.2.1
torch
requests
```

**Comment by tomhosking** [comment]
I think a whole bunch of build utilities were removed in cd1c45d5d9d81214483500f7a50560f9a9cd4ade - I had to reinstall them manually with something like `RUN apt-get update -y && apt-get install -y [...]`

**Comment by xiacijie** [comment]
@tomhosking Solved! Thank you!
