### ISSUE TITLE
Base image contains library with AGPL license

### ISSUE THREAD

**Issue by danjer2** [Azure/azure-functions-docker#1035]
I am using Node function apps using custom container. Currently using the base image `azure-functions/node:4.28.4-node18-slim`
I did an Xray scan, and besides the many vulnerabilities from Debian, it shows that the image contains the NuGet package [marain](https://www.nuget.org/packages/marain/4.0.0-system-text-json.7) which has an AGPL 3.0 license. My organization does not permit the use of AGPL libraries.

We need a clean base image that can be used commercially without restrictions.

**Comment by FinVamp1** [comment]
@danjer2 I looked at the AGPL 3.0 package and this comes from [Marain.Net (github.com)](https://github.com/marain-dotnet) which we don’t take a dependency on as far as I can tell.

I scanned the latest Node 4 Slim image and the 4.28.4 image for this and I don’t see this as a license issue to be addressed. Do you have steps to reproduce this?

trivy image mcr.microsoft.com/azure-functions/node:4.28.4-node18-slim --scanners license --license-full --license-confidence-level 0.8

If there are other steps I should follow then let me know. I tested also with a JFrog Xray scan using the Docker Desktop extension.




trivy image mcr.microsoft.com/azure-functions/node:4.28.4-node18-slim --scanners license --license-full --license-confidence-level 0.8

If there are other steps I should follow then let me know. I tested also with a JFrog Xray scan using the Docker Desktop extension.

**Comment by danjer2** [comment]
@FinVamp1 I'm trying to get details about our Xray configuration to try to understand why we're getting different results. We got the same policy violations using the base image 4.30.

The license issue is really odd, because it's a NuGet package. We're only adding NPM packages and JavaScript code, I can't image they add a NuGet dependency.  Also we get flagged on all our function apps, so if it's not in the base image, it has to be a very common package that we use everywhere.

Also an interesting detail (I realize I can't take it as a fact) - when I asked Copilot about the marain dependency, it told me that you're using it for the dotNet isolated instances. I could not verify the answer, but it sounded plausible.

**Comment by FinVamp1** [comment]
@danjer2  thanks. Looking at the package I don't see a reason for us to need this, but I will try and continue to investigate.

**Comment by FinVamp1** [comment]
Could you provide a cut down docker file that reproduces the issue?

**Comment by danjer2** [comment]
We're in discussion with JFrog to understand why their Xray reports the dependency, but no one is able to locate it. It feels like a false positive.

**Comment by FinVamp1** [comment]
Thanks. I'll check back next week and resolve this issue if you have heard back.

**Comment by danjer2** [comment]
We confirmed it was a problem with Xray. Probably holding on to some old information. Per JFrog recommendations, we re-indexed all the packages, and the AGPL violations went away.
Closing the issue as it was a false positive. Thank you for looking into it!

**Comment by FinVamp1** [comment]
Thanks @danjer2 for closing the loop on this one.
