### ISSUE TITLE
Cannot pass logging envronment variable down to the WebHost

### ISSUE THREAD

**Issue by aluong** [Azure/azure-functions-docker#11]
I have tried both ENV settings (It appears that WebHost has been updated [here](https://github.com/Azure/azure-functions-host/commit/1dae16ef2061de61ff0cd53b4140ba6443950a99) to use the second one):
```
ENV host:logger:consoleLoggingMode=always
ENV consoleLoggingMode=always
```

Undoing the following commit seems to allow it to work again:
[Commit 36b4bba6457501](https://github.com/Azure/azure-functions-docker/commit/36b4bba6457501a3c33d9e8c0df769d38e5180b0
)

**Comment by aluong** [comment]
I noticed that dev-nightly seems to work with: 
`ENV consoleLoggingMode=always`

Maybe something has changed in the WebHost, because I don't see anything different in the Dockerfile.

**Comment by asavaritayal** [comment]
@pragnagopa

**Comment by pragnagopa** [comment]
Yes. We have updated environment variable to consoleLoggingMode. Please udpate docker files. Here is the related issue that was fixed: https://github.com/Azure/azure-functions-host/issues/2759
