### ISSUE TITLE
Update .NET Isolated image to use 10XX host version

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-docker#1105]
When were ready to roll it out, we will need to update the .NET Isolated Dockerfiles' `HOST_VERSION` arguments to use the 4.10XX version of the host. This change will apply to all Linux SKUs.

**Comment by vmcbaptista** [comment]
Hi @mattchenderson do we have any ETA for when will this occur? From what I understand the 10XX has support for OpenTelemetry which is something me and my team will highly benefit. In fact this is something I've asked already here: https://github.com/Azure/azure-functions-host/issues/10258

**Comment by pragnagopa** [comment]
addressed in https://github.com/Azure/azure-functions-docker/commit/b46fd0af303443baf2f8c477ca56fc0af74fbac8#diff-fd12ca1fe12287f79136efc603b5c83d936a5870aba94d06d2d2ab5c5888351a

@vmcbaptista - best ETA for release production us by end of September 2024
