### ISSUE TITLE
Change python packages path to not have 3.6

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-docker#138]
Right now, we expect custom packages to be at `.python_packages/lib/python3.6/site-packages` location. We had it this way as we used to create a virtualenv before, which needed the packages to be there. 
Later, we went away from virtualenv but left the path to be in that format. Now that we want to support multiple versions of Python, we should get rid of `/python3.6` and just change it to `.python_packages/lib/site-packages`. `lib` is nice to have in case we start supporting `bin` in future.

For now, it's fine as all clients can continue having Python packages in `.python_packages/lib/python3.6/site-packages` even for Python 3.7.

This issue is just for cosmetics change to avoid confusion in future.

Thanks @Hazhzeng for bringing this up earlier.

**Comment by Hazhzeng** [comment]
We decided to have
**.python_packages/lib/python3.6/site-packages** for python3.6
and
**.python_packages/lib/site-packages** for future python versions
