### ISSUE TITLE
QueueTrigger question

### ISSUE THREAD

**Issue by mohsinonxrm** [Azure/azure-functions-docker#149]
I'm trying to run a simple queue trigger in a docker container on Raspberry Pi 4B:
`using System;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.Extensions.Logging;

namespace queuetrigger
{
    public static class queuetrigger
    {
        [FunctionName("queuetrigger")]
        public static void Run([QueueTrigger("myqueue-items", Connection = "")]string myQueueItem, ILogger log)
        {
            log.LogInformation($"C# Queue trigger function processed: {myQueueItem}");
        }
    }
}`

Dockerfile
`FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS installer-env

COPY . /src/dotnet-function-app
RUN cd /src/dotnet-function-app && \
    mkdir -p /home/site/wwwroot && \
    dotnet publish *.csproj --output /home/site/wwwroot

FROM mcr.microsoft.com/azure-functions/dotnet:2.0-arm32v7
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
	AzureWebJobsStorage=… 

COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]`

however, looks like the Azure Functions Host doesn't run and it just gives the below output:
`pi@raspberrypi:~/queueazfunc/queuetrigger/queuetrigger $ docker run queuetrigger:latest
Hosting environment: Production
Content root path: /
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.`

Queue messages stay in the queue, no outputs, nothing.

Please help me figure this out.

**Comment by ahmelsayed** [comment]
We don't maintain arm32 images.
