### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by mhumpher** [Azure/azure-functions-docker#162]
I have a Python function app that I'm trying to send a POST call to with about 2MB from a text file. Testing locally works fine, but when I publish to Azure I get this error:

```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

I start receiving this error when the POST size gets above about 200KB. I've tried Postman and curl to send the request, but I always get the same error.

**Comment by soninaren** [comment]
@mhumpher Looks like this is an issue web server configuration.

**Comment by saundersmatt** [comment]
I'm also seeing this error when posting files to a python function around 2MB.
Seems that nginx config has probably got the setting client_max_body_size 2M;
C# on windows limits to 100MB

**Comment by soninaren** [comment]
We are updating the config to to match what is set on function runtime. Should most likely go out in the next release.

**Comment by mhumpher** [comment]
@soninaren Thanks! Is there a timeline for the next release?

**Comment by anirudhgarg** [comment]
It should be a maximum of 2 weeks if not earlier

**Comment by ben-said** [comment]
Hi, I've also got the same issue - until the fix comes out, is there any way for us to updated the client_max_body_size manually for an nginx set-up?

**Comment by ahmelsayed** [comment]
@ben-said unfortunately it's not something you can do yourself. 
The update is rolling out now however.  It's already deployed in the South East Asia region, and other regions are in the deployment queue.

**Comment by ahmelsayed** [comment]
This should be addressed now.
