### ISSUE TITLE
azure functions 3 java runtime

### ISSUE THREAD

**Issue by Pamir** [Azure/azure-functions-docker#184]
Hi,
Building the docker image for azure java functions runtime 3 generates the error below

https://github.com/Azure/azure-functions-docker/blob/master/host/3.0/buster/amd64/java8.Dockerfile

Sending build context to Docker daemon  111.6kB
Step 1/12 : ARG BASE_IMAGE
Step 2/12 : FROM ${BASE_IMAGE} as runtime-image
base name (${BASE_IMAGE}) should not be blank

**Comment by ahmelsayed** [comment]
Old docker files required a build script to run them correctly. Current file should work with a single docker build command https://github.com/Azure/azure-functions-docker/blob/master/host/3.0/buster/amd64/java/java8/java8.Dockerfile
