### ISSUE TITLE
azure functions 2 java runtime failed to build image

### ISSUE THREAD

**Issue by Pamir** [Azure/azure-functions-docker#185]
Hi,
on macos building the image from the file below generates an error due to missing folder in mcr.microsoft.com/azure-functions/base:2.0-alpine

https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/alpine/amd64/java.Dockerfile

Sending build context to Docker daemon  111.6kB
Step 1/13 : ARG BASE_IMAGE=mcr.microsoft.com/azure-functions/base:2.0-alpine
Step 2/13 : FROM ${BASE_IMAGE} as runtime-image
 ---> c8de0c6f03a4
Step 3/13 : FROM openjdk:8-jdk-alpine as jdk
 ---> 6eb8392704ff
Step 4/13 : RUN mkdir -p /usr/lib/jvm/java-1.8-openjdk
 ---> Using cache
 ---> 5526bdfa2f5e
Step 5/13 : FROM mcr.microsoft.com/dotnet/core/runtime-deps:2.2-alpine
 ---> 23fa57f40aea
Step 6/13 : RUN apk add --no-cache libc6-compat libnsl &&     ln -s /usr/lib/libnsl.so.2 /usr/lib/libnsl.so.1
 ---> Using cache
 ---> fbc2319f25fb
Step 7/13 : ENV AzureWebJobsScriptRoot=/home/site/wwwroot     HOME=/home     FUNCTIONS_WORKER_RUNTIME=java
 ---> Using cache
 ---> 9cba9f8ca327
Step 8/13 : COPY --from=runtime-image [ "/azure-functions-host", "/azure-functions-host" ]
 ---> Using cache
 ---> 49fce91a9b35
Step 9/13 : COPY --from=runtime-image [ "/workers/java", "/azure-functions-host/workers/java" ]
 ---> Using cache
 ---> 19c4ddde01d4
Step 10/13 : COPY --from=runtime-image [ "/FuncExtensionBundles", "/FuncExtensionBundles" ]
COPY failed: stat /var/lib/docker/overlay2/1b1ce5173874626f892dd767cd3e291f82360955985597de8dc5dd394f46aba9/merged/FuncExtensionBundles: no such file or directory

mcr.microsoft.com/azure-functions/base:2.0-alpine image contains the folders below in the root level
drwxr-xr-x    2 root     root          4096 Dec 20  2018 srv
drwxr-xr-x    2 root     root          4096 Dec 20  2018 sbin
drwxr-xr-x    2 root     root          4096 Dec 20  2018 run
drwx------    2 root     root          4096 Dec 20  2018 root
drwxr-xr-x    2 root     root          4096 Dec 20  2018 mnt
drwxr-xr-x    5 root     root          4096 Dec 20  2018 media
drwxr-xr-x    2 root     root          4096 Dec 20  2018 bin
drwxr-xr-x    1 root     root          4096 Jan 14  2019 var
drwxr-xr-x    1 root     root          4096 Jan 14  2019 usr
lrwxrwxrwx    1 root     root             3 Jan 22  2019 lib64 -> lib
drwxr-xr-x    1 root     root          4096 Jan 22  2019 lib
drwxr-xr-x    4 root     root          4096 Jan 22  2019 azure-functions-host
drwxr-xr-x    5 root     root          4096 Jan 22  2019 workers
dr-xr-xr-x   13 root     root             0 Dec  7 22:53 sys
dr-xr-xr-x  220 root     root             0 Dec  7 22:53 proc
drwxr-xr-x    1 root     root          4096 Dec  7 22:53 etc
drwxr-xr-x    5 root     root           340 Dec  7 22:53 dev
-rwxr-xr-x    1 root     root             0 Dec  7 22:53 .dockerenv
drwxr-xr-x    1 root     root          4096 Dec  7 22:53 ..
drwxr-xr-x    1 root     root          4096 Dec  7 22:53 .
drwxrwxrwt    1 root     root          4096 Dec  7 22:53 tmp
drwxr-xr-x    1 root     root          4096 Dec  7 22:53 home

**Comment by Pamir** [comment]
Hi,
I think i have fond the solution. First of all we should build the base image  which is https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/alpine/amd64/base.Dockerfile

docker build . -f AzureBase.dockerfile -t mcr.microsoft.com/azure-functions/base:2.0-alpine 
After building the image with approproate tag without pushing to docker registry we should build the java docker file.
docker build . -t java-functions-sample

container image in mcr.microsoft.com/azure-functions/base:2.0-alpine  and the dockerfile in https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/alpine/amd64/base.Dockerfile are different which have not been  pushed to registry. Only building the java image generates this error. I think we should build and upload the base image with appropriate version and fix the java dockerfile.

Regards
Pamir

**Comment by AayushiKhandelwal123** [comment]
@Pamir, were you able to create  running docker image for function app in java

**Comment by SimoneCusimano** [comment]
any news?

**Comment by Pamir** [comment]
Just give me couple of days. I will try again and let you know

**Comment by ahmelsayed** [comment]
https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/alpine/amd64/java/java8.Dockerfile 

should work for java on alpine for v2 functions.
