### ISSUE TITLE
Provide a way to set "CORS allowed origins"

### ISSUE THREAD

**Issue by vnom2112** [Azure/azure-functions-docker#187]
I am trying to use the dotnet docker image to run e2e tests in a CI/CD pipeline.  I have a container that run the function app, and another that run the angular app with the e2e tests.  I use docker compose to run them.  The problem I am running into is I cannot set the CORS allowed origin to '*' to run my e2e tests from headless chrome.  In my docker-compose file I tried setting the env variable `CORS_ALLOWED_ORIGINS: '*'`, however, I continued to get cors errors when headless chrome tries to hit the function app.  I pulled the above env variable from the following library (which seems to be the library used to run the dotnet function app in docker, please correct me if I am wrong here): https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Environment/EnvironmentSettingNames.cs

Am I missing something here, or is there just not a way to set cors in the dotnet docker container?

**Comment by kvaes** [comment]
Linked to https://github.com/Azure/azure-functions-host/issues/5090 ?

**Comment by ahmelsayed** [comment]
Closing external issue as I don't think the docker images change the behavior of the runtime.
