### ISSUE TITLE
Broken links on DH README

### ISSUE THREAD

**Issue by jlk** [Azure/azure-functions-docker#198]
Guys - just noticed on https://hub.docker.com/_/microsoft-azure-functions-base a good number of the links to Dockerfiles for the various images (under Featured Tags) are broken. eg https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/stretch/amd64/powershell.Dockerfile should point to https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/stretch/amd64/powershell6.Dockerfile instead.

Looks like the Dockerfile names were updated to include versions, but the DH page needs tweaking.

I'd offer a PR, but I don't think that page comes from this repo?

**Comment by ahmelsayed** [comment]
The docs on docker hub come from another repo owned by the MCR team that manages the images on dockerhub for us. The docs there were updated a couple of months ago and should point to the correct dockerfiles.
