### ISSUE TITLE
No Console Logging

### ISSUE THREAD

**Issue by sandersonatlatitude** [Azure/azure-functions-docker#24]
In the  latest build all console logging of errors is gone, and my queueTrigger do not start .
Using microsoft/azure-functions-node8:2.0

**Comment by jmo808** [comment]
The python version has similar issues, I can't get any type of function to work.

**Comment by asavaritayal** [comment]
This issue was moved to Azure/azure-functions-host#3469

**Comment by yubozhao** [comment]
The console log is still missing for the python docker image, when the envvar `AzureFunctionsJobHost__Logging__Console__IsEnabled` is set to true.  

I am using docker image base: mcr.microsoft.com/azure-functions/python:3.0.13901-python3.7.
