### ISSUE TITLE
Unable to start 3.0-bionic-arm32v7 image 

### ISSUE THREAD

**Issue by fksik** [Azure/azure-functions-docker#246]
The image 3.0-bionic-arm32v7 is not starting.
I am getting this error 

standard_init_linux.go:211: exec user process caused "exec format error"

My docker file is as follows

FROM mcr.microsoft.com/azure-functions/dotnet:3.0-bionic-arm32v7
COPY ./ /home/site/wwwroot

**Comment by ahmelsayed** [comment]
`:3.0-bionic-arm32v7` is an arm32v7 image. You can try 

```
sudo apt-get install qemu binfmt-support qemu-user-static
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes 
```
