### ISSUE TITLE
Azure portal cannot list my functions anymore

### ISSUE THREAD

**Issue by Tetradeus** [Azure/azure-functions-docker#25]
Hello,

Azure portal is not listing my functions anymore. May it comes from recent changes ?

When azure portal tries to list my functions in the interface, it tries to access /admin/functions and here is the result :

OPTIONS https://xxxxxxx.azurewebsites.net/admin/functions 404 ()
Failed to load https://xxxxxxx.azurewebsites.net/admin/functions: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://functions.azure.com' is therefore not allowed access.
POST https://functions.azure.com/api/passthrough 500 (Internal Server Error)

I am not sure if it may comes from the docker image.
I am using 2.0 tag. Does the image behind this tag change overtime ? If yes it would be great to have immutable docker image tag.

Docker image is from microsoft/azure-functions-base:2.0

**Comment by Tetradeus** [comment]
After redeploying, the ui finally get to print my functions but it only works one time....
The problem looks to me more on the second call :
POST https://functions.azure.com/api/passthrough 500 (Internal Server Error)
POST /api/passthrough HTTP/1.1
Host: functions.azure.com
Connection: keep-alive
Content-Length: 447
Origin: https://functions.azure.com
content-type: application/json
Accept: application/json, text/plain, */*

{
  "method": "GET",
  "url": "https://xxxxxx.azurewebsites.net/admin/functions",
  "body": "null",
  "headers": {
    "Authorization": "Bearer xxxxx"
  }
}

HTTP/1.1 500 Internal Server Error
Server: Kestrel
Set-Cookie: ARRAffinity=xxxxx;Path=/;HttpOnly;Domain=functions.azure.com
request-context: appId=cid-v1:xxxx
X-Powered-By: Express
X-Powered-By: ASP.NET
Date: Mon, 10 Sep 2018 21:52:37 GMT
Content-Length: 0

**Comment by asavaritayal** [comment]
This issue was moved to Azure/azure-functions-ux#3166
