### ISSUE TITLE
Http triggers and ssl

### ISSUE THREAD

**Issue by carlwoodhouse** [Azure/azure-functions-docker#254]
Hi,

Might have missed it but i can't seem to find a way or any documentation on how i can use ssl with a http trigger running in a functions docker container.

Anyone know?

**Comment by carlwoodhouse** [comment]
Ok closing this ... you just need to configure it in the exact same way you configure kestrel for aspnetcore :)

**Comment by davidivkovic** [comment]
Can you provide more details please?
