### ISSUE TITLE
Nanoserver images for azure function V3 not available

### ISSUE THREAD

**Issue by mail2hjain** [Azure/azure-functions-docker#265]
While pulling the docker image for azure function V3 for nanoserver-1809, it is failing with below error: 

>docker pull mcr.microsoft.com/azure-functions/dotnet:3.0-nanoserver-1809
Error response from daemon: manifest for mcr.microsoft.com/azure-functions/dotnet:3.0-nanoserver-1809 not found: manifest unknown: manifest tagged by "3.0-nanoserver-1809" is not found

**Comment by ahmelsayed** [comment]
This should be working now.
