### ISSUE TITLE
How to enable authorization for Azure Function[HttpTrigger] as module in IoT Edge?

### ISSUE THREAD

**Issue by sagunase** [Azure/azure-functions-docker#273]
I am using HttptTrigger Azure Function as module in IoT edge device and can be accessed only within the private network, w.r.t, I want to build Authorization for Httptrigger endpoint. 
Looking for the best practice to securely access the endpoint and also can you please share sample docs.

**Comment by ahmelsayed** [comment]
Please refer to documentation of Azure Functions over at https://docs.microsoft.com/en-us/azure/azure-functions/functions-overview
