### ISSUE TITLE
Minor update to Python image 

### ISSUE THREAD

**Issue by eduardomourar** [Azure/azure-functions-docker#28]
As per [official Python docker image](https://github.com/docker-library/python/blob/master/3.6/stretch/slim/Dockerfile), could we add some important environment variables:
```
ENV LANG C.UTF-8
ENV PYTHON_VERSION 3.6.6
ENV PYTHON_PIP_VERSION 18.0
```

Also, while at it, why don't we update to version 3.6.6. I have been doing some tests and, so far, not a single problem.

**Comment by elprans** [comment]
No objections.

**Comment by ankitkumarr** [comment]
Currently, we install and upgrade pip to the latest version. Just setting `ENV PYTHON_PIP_VERSION 18.0` explicitly may cause version mismatch in the future. 

I could change it to download specifically pip version 18.0, and then set `ENV PYTHON_PIP_VERSION 18.0`. Would that be ok, @elprans.

**Comment by elprans** [comment]
I don't think those environment variables affect anything but the Dockerfile recipe itself.  Python and pip themselves certainly don't care.

**Comment by eduardomourar** [comment]
My point (based on python official image) is to have an easy way to check what python and pip version has been installed. So it would be nice to have version of pip installed that match the environment variable.

**Comment by elprans** [comment]
Yes, of course, the vars should match the actual versions installed.  The easiest way to achieve that is to use the vars when installing, e.g `pip install pip==${PYYTHON_PIP_VERSION}`

**Comment by ankitkumarr** [comment]
Right, that's what I meant to double check because currently, we are getting the latest upgrade of pip. Ok to install specifically version 18?

**Comment by elprans** [comment]
I see no problems with that.
