### ISSUE TITLE
[question] Azure function with windows container ?

### ISSUE THREAD

**Issue by agouriou** [Azure/azure-functions-docker#285]
Hi,

I see on this repo some windows images, eg: 2.0-nanoserver-1809 for dotnet.

However, the documentation of azure function says it's only possible to run linux containers:
[https://docs.microsoft.com/fr-fr/azure/azure-functions/functions-deployment-technologies#docker-container](https://docs.microsoft.com/fr-fr/azure/azure-functions/functions-deployment-technologies#docker-container)

Is the documentation wrong ? Is it possible to use one of the windows images of this repo to run on azure function ?

Thanks

**Comment by ahmelsayed** [comment]
When deploying on AppService, only Linux Containers are supported. Windows deployments don't use containers. There is a Windows container image however if you want to run your functions on your own Windows containers host.

**Comment by DadvDadv** [comment]
"There is a Windows container image however if you want to run your functions on your own Windows containers host"
This is what i wan't to do (for dev), could you tell me what image to take please ?
