### ISSUE TITLE
PowerShell 3.0 Buster Base Image

### ISSUE THREAD

**Issue by AdamCoulterOz** [Azure/azure-functions-docker#325]
The `mcr.microsoft.com/azure-functions/powershell:3.0` image with the Dockerfile here (azure-functions-docker/host/3.0/**buster**/amd64/powershell/powershell6.Dockerfile) is built from a base of `mcr.microsoft.com/dotnet/core/aspnet:2.2` which is actually `debian-stretch` not `debian-buster` as indicated. This needs to be updated to have a base of `mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim`. 

Until this change is made the guidance on what container to use for PowerShell functions is broken. 

- https://hub.docker.com/_/microsoft-azure-functions-powershell
- https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image?tabs=bash%2Cportal&pivots=programming-language-powershell

https://github.com/Azure/azure-functions-docker/blob/5b4da7a6be22d469dc8537a270c5441310d204ac/host/3.0/buster/amd64/powershell/powershell6.Dockerfile#L32-L59

**Comment by AdamCoulterOz** [comment]
also this one if possible? @anthonychu

**Comment by anthonychu** [comment]
@TsuyoshiUshio @AnatoliB Can you please take a look?

**Comment by AdamCoulterOz** [comment]
PR #328 addresses this problem for me, but technically all the images which claim to be `buster` but are pointing at aspnet:2.1 are actually still `stretch`. To support powershell 6 you'll need a base image which is based on `buster-slim` and has both dotnet core 2 and 3 included, as powershell 6 uses dotnet core 2.

**Comment by AnatoliB** [comment]
As PowerShell 6 has reached end-of-life, we want to minimize further investments in maintaining PowerShell 6 images, so I propose closing this issue. The new PowerShell 7 images are already based on `buster`, so we will encourage you to use those. Please let us know if you have any special reason to continue using PowerShell 6 images **and** have them updated to `buster`.

**Comment by AdamCoulterOz** [comment]
Fine for that logic... then update the docs to not indicate there is buster support for PS6 when there isn't. But thanks for the PS7 buster update.
