### ISSUE TITLE
Azure Functions & Node 14 Support

### ISSUE THREAD

**Issue by antempus** [Azure/azure-functions-docker#354]
With Azure Functions support Node 14 now in [GA/Preview](https://azure.microsoft.com/en-us/updates/nodejs-14-for-azure-functions-is-now-available-in-preview/), it would be great to see a Node 14 container available for use with DevContainers for migration work.

**Comment by divyagandhii** [comment]
@antempus There is a Node14 image available for use [/azure-functions-docker/tree/master/host/3.0/buster/amd64/node/node14](https://github.com/Azure/azure-functions-docker/tree/master/host/3.0/buster/amd64/node/node14)
