### ISSUE TITLE
Microsoft ODBC Driver 17 for SQL Server - Python

### ISSUE THREAD

**Issue by Rye6** [Azure/azure-functions-docker#37]
I'd like to be able to connect from a Python Azure Function in the 2.0 runtime (consumption plan) to an Azure SQL Server 17 database.

Currently receiving the error: `OdbcNoLibrary: ODBC Library is not found.` which should be resolved by #32, but I believe the correct driver would also need to be installed for unixodbc to actually make the connection. I found instructions for that here: https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017 .

Could we have this driver installed to the base image for Python Azure Functions, to enable out-of-the-box SQL Server 17 connectivity?

**Comment by ahmelsayed** [comment]
should be fixed in 77e57d37cdbeb27ea17b12c54a8c79f40376eca5

**Comment by Rye6** [comment]
I believe the particular SQL Server driver needs to be made available as described above. With the changes you mentioned, my error advanced from `OdbcNoLibrary: ODBC Library is not found.` to `('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found")`.

If I'm mistaken and this is working as intended, could you advise on what needs to be changed for this to work with the current installation? If it helps clarify, I'm trying to use the pypyodbc library and the SQL Server driver mentioned in the error above.

**Comment by daigotanaka** [comment]
@Rye6 I don't know if you figure out but I was successful by not hard-coding the driver version:
```
driver = sorted(pyodbc.drivers()).pop()
```

**Comment by endersonmenezes** [comment]
This worked for me
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017#microsoft-odbc-driver-131-for-sql-server

**Comment by endersonmenezes** [comment]
> I believe the particular SQL Server driver needs to be made available as described above. With the changes you mentioned, my error advanced from `OdbcNoLibrary: ODBC Library is not found.` to `('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found")`.
> 
> If I'm mistaken and this is working as intended, could you advise on what needs to be changed for this to work with the current installation? If it helps clarify, I'm trying to use the pypyodbc library and the SQL Server driver mentioned in the error above.

This worked for me
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017#microsoft-odbc-driver-131-for-sql-server
