### ISSUE TITLE
python.Dockerfile is using an old version of the worker

### ISSUE THREAD

**Issue by daxian-dbw** [Azure/azure-functions-docker#39]
It seems `python.Dockerfile` is pulling in an old version (`1.0.0a4`) of the worker's source code, is that intentional? If not, please update to use the latest release `1.0.0a6`

https://github.com/Azure/azure-functions-docker/blob/701bb7c37089bb1bf312f950563839aacf53287d/host/2.0/stretch/amd64/python.Dockerfile#L3-L13

**Comment by pragnagopa** [comment]
@maiqbal11 - Please update the docker file?

**Comment by maiqbal11** [comment]
Created PR #42 for this

**Comment by pragnagopa** [comment]
> /cc @pragnagopa can you make sure to include updating the reference here to your process of updating python worker versions?

I will update the release process to include docker file updates.

Thanks @daxian-dbw  for opening the issue!

**Comment by daxian-dbw** [comment]
I guess both the `functions-python` and `functions-powershell` docker images need to be refreshed in MCR now.

**Comment by ahmelsayed** [comment]
`:dev` tag is being built. Updating `2.0` and `latest` tags is manual. I'll push an update once dev is done

**Comment by ahmelsayed** [comment]
@maiqbal11 sorry looks like we use that version for both `azure-functions` and `azure-functions-worker` the CI is failing with 

```
Could not find a version that satisfies the requirement azure-functions==1.0.0a6 (from versions: 1.0.0a1, 1.0.0a3, 1.0.0a4, 1.0.0a5)
```

I think you may wanna add another setting since the 2 are diverging now.
