### ISSUE TITLE
Some dependencies exist in Consumption mesh image but NOT Dedicated image

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-docker#407]
This causes a difference in behavior when customers try to switch between the two. We should consider keeping the installed dependencies consistent.

In particular, these headless chrome dependencies:
https://github.com/Azure/azure-functions-docker-private/blob/dev/host/3.0/buster/amd64/mesh-py39.Dockerfile#L104-L108

Which are not present here:
https://github.com/Azure/azure-functions-docker/blob/dev/host/3.0/buster/amd64/python/python39/python39.Dockerfile

Public mirror issue of: https://github.com/Azure/azure-functions-docker-private/issues/164

**Comment by mhoeger** [comment]
@pragnagopa - Could this be triaged? We have a customer asking for some ETA. Thanks!

**Comment by mhoeger** [comment]
+@saranyaravichander who is following this issue

**Comment by pragnagopa** [comment]
Thanks for flagging this @mhoeger ! Assigning to @CooperLink  - to see if this can be done as part of refactoring work he is currently looking into.

**Comment by pragnagopa** [comment]
cc @ahmelsayed

**Comment by nicjohn79** [comment]
@CooperLink Please let us know if this can be done with the refactoring work. We have a large customer who would like an ETA as this is a blocker for them.

**Comment by ahmelsayed** [comment]
https://github.com/Azure/azure-functions-docker/pull/417

**Comment by nicjohn79** [comment]
@ahmelsayed Does this mean the chrome headless dependencies will be added to the following docker image?:
https://github.com/Azure/azure-functions-docker/blob/dev/host/3.0/buster/amd64/python/python39/python39.Dockerfile

**Comment by ahmelsayed** [comment]
yes, I guess I missed 3.9 in that PR. https://github.com/Azure/azure-functions-docker/pull/420

**Comment by nicjohn79** [comment]
Thanks @ahmelsayed! Do you have a date when the 3.9 image will be available for download?

**Comment by balag0** [comment]
We are preparing for a release this week, so should be available sometime next week.

**Comment by nicjohn79** [comment]
Hi Bala,

Is the new image ready now?

Best Regards,

Nicole Johnson
Azure Customer Engineer II
Advanced Cloud Engineering (ACE)
Office: +1 (469) 7753644
***@***.******@***.***>
Wrk hrs: Mon-Fri 9-6 PM CST
[Microsoft Logo]
If you have any feedback about my work, please let either myself or my manager know at ***@***.******@***.***>

**Comment by nicjohn79** [comment]
@balag0 is the new image ready for download now?
