### ISSUE TITLE
[Powershell]Copy only Linux Runtimes folder for Powershell worker

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-docker#418]
Powershell Image: `mcr.microsoft.com/azure-functions/powershell:3.0.15417-powershell7-appservice`

has the following:

```
root@a78c1b423bac:/# ls azure-functions-host/workers/powershell/7/runtimes/
freebsd  linux-arm    linux-musl-x64  osx      unix  win-arm    win-x64  win10-x64  win7-x64  win8-x64  win81-x64
linux    linux-arm64  linux-x64       osx-x64  win   win-arm64  win-x86  win10-x86  win7-x86  win8-x86  win81-x86
root@a78c1b423bac:/#
```

Deleting Windows specific folders will save ~35MB

**Comment by CooperLink** [comment]
Resolved by removing windows runtimes for Powershell 7 and removing powershell 6 from the FunctionsHost base image. Will revert Powershell 6 to be independent of FunctionsHost base image.

**Comment by pragnagopa** [comment]
Removing Powershell 6 from base image to as we do not plan to support powershell 6 on Linux
