### ISSUE TITLE
Update docker images to use extension bundles from bundles release rather than cdn

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-docker#434]
ExtensionBundles in docker images - pull bundles from CDN:

https://github.com/Azure/azure-functions-docker/blob/dev/host/3.0/buster/amd64/java/java11/java11.Dockerfile#L22

This requires us to push bundles to CDN before starting Linux deployment.

We need to be using bundles from : https://github.com/Azure/azure-functions-extension-bundles/releases to ensure bundles are deployed to Azure before releasing to Cdn

**Comment by soninaren** [comment]
CDN update is already part of the build and happens automatically before the PR step. Closing this issue, as this is a no-op.
