### ISSUE TITLE
Azure SDKs native in Functions

### ISSUE THREAD

**Issue by dariagrigoriu** [Azure/azure-functions-docker#46]
Specific customer feedback indicates the experience in Functions can be improved by making Azure SDKs native in Functions (currently requires packaging SDK and uploading). This would create an experience for Functions more aligned to a principle of “inter-connected tissue” to facilitate serverless to hook among the services within Azure.

**Comment by asavaritayal** [comment]
Adding link to the corresponding Python issue - https://github.com/Azure/azure-functions-docker/issues/14 and community discussion.

**Comment by ahmelsayed** [comment]
we're not doing this
