### ISSUE TITLE
Install Microsoft odbc driver for sql server in python image

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-docker#47]
Python function apps using pyodbc to connect to Azure SQL are failing with 
('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'SQL Server' : file not found (0) (SQLDriverConnect)")

Instructions to install:
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017

**Comment by asavaritayal** [comment]
There's a PR for this - https://github.com/Azure/azure-functions-docker/pull/45

**Comment by ahmelsayed** [comment]
Fixed in #45
