### ISSUE TITLE
[V4 Images] Powershell core tools docker build fails with - "powershell : Depends: libicu63 but it is not installable"

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-docker#475]
In 4\bullseye\amd64\powershell\powershell7-core-tools.Dockerfile

step
apt install -y /tmp/powershell.deb

fails with
#7 39.95  powershell : Depends: libicu63 but it is not installable
#7 39.97 E: Unable to correct problems, you have held broken packages.

+ @Francisco-Gamino

**Comment by pragnagopa** [comment]
@AnatoliB - Assigned to you for now. Please find an owner
