### ISSUE TITLE
Add test to ensure staged publish includes images listed in publish

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-docker#480]
Add test that verifies - images in - https://github.com/Azure/azure-functions-docker/blob/dev/host/3.0/publish.yml are included in https://github.com/Azure/azure-functions-docker/blob/dev/host/3.0/publish-appservice-stage.yml

**Comment by pragnagopa** [comment]
cc @CooperLink @balag0 @yojagad @divyagandhisethi

**Comment by pragnagopa** [comment]
Related issue #493

**Comment by CooperLink** [comment]
Tagging PR that fixes this issue : https://github.com/Azure/azure-functions-docker/pull/500

All -appservice images must be accounted for in both pipelines (except for base image) in order for PR+Upgrade to work.
