### ISSUE TITLE
[V4 Images] V4 Python images are using python:3.9-slim-buster base images

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-docker#481]
There is no python:3.9-slim-bullseye image available currently.
Need to confirm if using the buster image is okay from functionality point of view.

+@vrdmr

**Comment by linoecarrillo** [comment]
@balag0 python:3.9-slim-bullseye image is now available: https://github.com/docker-library/python/blob/f154e5d1c8f5b582aa2fd782df880b9cc96bb431/3.9/bullseye/slim/Dockerfile

**Comment by pragnagopa** [comment]
@vrdmr - assigned to you for now. Please find an owner.
