### ISSUE TITLE
Azure Functions with Docker on M1 machine

### ISSUE THREAD

**Issue by iamNoah1** [Azure/azure-functions-docker#487]
I am trying to run Azure Functions with Docker on a M1 machine without success so far. Is my assumption right, that there is no base image for arm M1 architecture at the moment?

**Comment by balag0** [comment]
Correct.

**Comment by iamNoah1** [comment]
any plans for future support?

**Comment by balag0** [comment]
No, not currently. Are you able to use the dockerfiles in this repo and update the base os images as required and give it a try?

**Comment by iamNoah1** [comment]
Could give it a try at least :)

**Comment by mohsinonxrm** [comment]
@iamNoah1 , any luck?

**Comment by iamNoah1** [comment]
@mohsinonxrm nope, not yet

**Comment by mohsinonxrm** [comment]
@iamNoah1 , well looks like the Extensions will need to built for v4/.net6, so that's a dependency and then also building the actual tools which I was able to build, so not completely there.

**Comment by stephen776** [comment]
Any updates to this? Anyway to get this to work?

**Comment by papakpmartin** [comment]
+1 wishing this would work.

I wonder what the hold up is? Azure Functions Core Tools [has arm64](https://github.com/Azure/azure-functions-core-tools/releases/tag/4.0.4544) builds now. This repo has related issues on it (#224 and #402) that are well over a year old.

Can we get some guidance, please?

**Comment by papakpmartin** [comment]
@balag0 and/or @anirudhgarg, do there continue to be no plans to support this (per [comment above](https://github.com/Azure/azure-functions-docker/issues/487#issuecomment-908583770))?

It _seems_ as though this [might be a work in progress](https://github.com/Azure/azure-functions-docker/tree/dev/host/4/bullseye/amd64)?

**Comment by mohsinonxrm** [comment]
@iamNoah1 , @stephen776 , @papakpmartin :
so... I was just revisiting this and thought I'll give it another go. 

BTW, I don't have a Mac and so only linux-arm64

First, I built the extensions from latest 2.x and 3.x branches for Linux arm64.
Then I rebuilt the Function Host for Linux arm64.
Then I got the docker files from the release and rebuilt them for Linux arm64.

Here are the results:
https://hub.docker.com/r/mohsinonxrm/azure-functions-dotnet/tags
mohsinonxrm/azure-functions-dotnet:4-appservice-arm64v8
mohsinonxrm/azure-functions-dotnet:4-isolated6.0-appservice-arm64v8

Images are multi-architecture now:
mohsinonxrm/azure-functions-dotnet:4-isolated6.0-appservice
mohsinonxrm/azure-functions-dotnet:4-isolated6.0
mohsinonxrm/azure-functions-dotnet:4-appservice
mohsinonxrm/azure-functions-dotnet:4

I haven't tried these and have no idea if they're working or not.

Anyway, give it a go and let me know if it works.

I guess, I've built the function cli for Linux ARM64 as well (couple years ago, so I need to recompile the v4).

The images were built on Azure's new Ampere ARM64 VMs on Ubuntu 20.4 Gen 2.

@balag0 , let me know if I'm working in the right direction or not? I could only find the appservice docker files in the release. I reviewed the release workflow, so not sure where the other combined files are going.

**Comment by oandreassen** [comment]
> https://hub.docker.com/r/mohsinonxrm/azure-functions-dotnet/tags

I can verify that this solved the issue on a M1 mac.

**Comment by iamNoah1** [comment]
@mohsinonxrm thanks for the efforts. Have you done everything locally/manually? It would be awesome to have your efforts in some gitrepo :)

**Comment by mohsinonxrm** [comment]
@iamNoah1 , yes, everything was done locally. However, note that apart from making some slight changes like runtime targets from dotnet, I didn't have to change anything else. If we build natively on AMD64 and ARM64, we wouldn't even need to provide those. 

Most of the changes were done in the Dockerfiles and I remember I used the steps from the workflow action to first generate the /out (release) version of Dockerfiles and then edited those to release linux-arm64 versions.

That's the bulk of it really.

Most of the work done was on the extensions project. All those changes are in my own GitHub fork, so feel free to review.

But yeah, I think I'll fork out azure-functions-docker and check-in my changes in the Dockerfiles for anyone to review.

I compiled the func cli as well, but that was also just editing the runtime id to be linux-arm64

**Comment by 0gust1** [comment]
@mohsinonxrm thanks a lot ! 
Hoping to see this landing on official Azure images.

**Comment by abailey7** [comment]
@mohsinonxrm I'm interested in the work here as well. Do you know if this has been merged in yet? We've been waiting for official arm64 support for Azure Functions Docker images since Apple Silicon was launched.

**Comment by arcogabbo** [comment]
> @iamNoah1 , yes, everything was done locally. However, note that apart from making some slight changes like runtime targets from dotnet, I didn't have to change anything else. If we build natively on AMD64 and ARM64, we wouldn't even need to provide those.
> 
> Most of the changes were done in the Dockerfiles and I remember I used the steps from the workflow action to first generate the /out (release) version of Dockerfiles and then edited those to release linux-arm64 versions.
> 
> That's the bulk of it really.
> 
> Most of the work done was on the extensions project. All those changes are in my own GitHub fork, so feel free to review.
> 
> But yeah, I think I'll fork out azure-functions-docker and check-in my changes in the Dockerfiles for anyone to review.
> 
> I compiled the func cli as well, but that was also just editing the runtime id to be linux-arm64

can you give us an image for the arm64 compiled func cli? I can't seem to find the binary in the containers you published. 
Thanks in advance for this great work ❤️ .

**Comment by demshy** [comment]
I stumbled upon this one and found this, just when I was about to give up:
https://levelup.gitconnected.com/docker-on-apple-silicon-mac-how-to-run-x86-containers-with-rosetta-2-4a679913a0d5

Not really the solution to this issue, but at least I can continue until the proper build is released (if ever). 
So basically what I did:
- update docker to 4.16.2
- enable "Use rosetta for x86/amd64 ... " option in settings > Features in development"
- set platform to "linux/amd64" in docker-compose

**Comment by mohsinonxrm** [comment]
I've just updated the multi-architecture images with the latest release, host and added dotnet 7 and 8-preview.

https://hub.docker.com/r/mohsinonxrm/azure-functions-dotnet/tags

mohsinonxrm/azure-functions-dotnet:4-isolated8.0-appservice-preview
mohsinonxrm/azure-functions-dotnet:4-isolated8.0-preview
mohsinonxrm/azure-functions-dotnet:4-isolated7.0-appservice
mohsinonxrm/azure-functions-dotnet:4-isolated7.0
mohsinonxrm/azure-functions-dotnet:4-isolated6.0-appservice
mohsinonxrm/azure-functions-dotnet:4-isolated6.0
mohsinonxrm/azure-functions-dotnet:4-appservice
mohsinonxrm/azure-functions-dotnet:4

_Not to be used in any official or supported capacity, certainly not in production_

**Comment by iamNoah1** [comment]
> I stumbled upon this one and found this, just when I was about to give up: https://levelup.gitconnected.com/docker-on-apple-silicon-mac-how-to-run-x86-containers-with-rosetta-2-4a679913a0d5
> 
> Not really the solution to this issue, but at least I can continue until the proper build is released (if ever). So basically what I did:
> 
> * update docker to 4.16.2
> * enable "Use rosetta for x86/amd64 ... " option in settings > Features in development"
> * set platform to "linux/amd64" in docker-compose

omg, thank you so much.

**Comment by adjaydev** [comment]
> I stumbled upon this one and found this, just when I was about to give up: https://levelup.gitconnected.com/docker-on-apple-silicon-mac-how-to-run-x86-containers-with-rosetta-2-4a679913a0d5
> 
> Not really the solution to this issue, but at least I can continue until the proper build is released (if ever). So basically what I did:
> 
> * update docker to 4.16.2
> * enable "Use rosetta for x86/amd64 ... " option in settings > Features in development"
> * set platform to "linux/amd64" in docker-compose

Yes! This is the one! Thank you ❤️

**Comment by jsoconno** [comment]
Here is a step-by-step guide for those looking to be able to quickly clone a repo and get started using Azure Functions with Docker + Nginx + Python 3.9.

https://github.com/onwardplatforms/azure-functions-apple-arm-chip-starter

Also, apparently, there is some support now for Apple silicon, but I still had issues with my M2 Mac using Python:

https://azure.microsoft.com/en-us/updates/generally-available-azure-functions-support-on-apple-silicon-macs/#:~:text=Published%20date%3A%20December%2006%2C%202023,%2C%20and%20Java%2011%20%26%2017.

**Comment by iamNoah1** [comment]
I think this can be closed now :)
