### ISSUE TITLE
3.0-python3.9-core-tools not available to download

### ISSUE THREAD

**Issue by JackCaster** [Azure/azure-functions-docker#499]
Is the image `mcr.microsoft.com/azure-functions/python/3.0-python3.9-core-tools` available to download? I can't seems to be able to use it. Here, for example, it is not listed: https://mcrflowprodcentralus.data.mcr.microsoft.com/mcrprod/azure-functions/python?P1=1631616167&P2=1&P3=1&P4=etS4ZUbzMrMeSv8lGYZp3X7kAkJMENBrrS6MMTlKwW4%3D&se=2021-09-14T10%3A42%3A47Z&sig=sqcaSdqtC6pFnoRuvOEVppU5FkAZMaozb1lK40m%2F7xs%3D&sp=r&sr=b&sv=2015-02-21

EDIT. If I use the docker file [here](https://raw.githubusercontent.com/Azure/azure-functions-docker/dev/host/3.0/buster/amd64/python/python39/python39-core-tools.Dockerfile) I get the error: `E: Unable to locate package azure-functions-core-tools-3`

**Comment by balag0** [comment]
Are you able to use python3.8 image instead?
mcr.microsoft.com/azure-functions/python:3.0-python3.8-core-tools

Looks like only python3.8 core tools image is being published now
https://github.com/Azure/azure-functions-docker/blob/dev/host/3.0/core-tools-publish.yml#L265

**Comment by JackCaster** [comment]
> Are you able to use python3.8 image instead?
> mcr.microsoft.com/azure-functions/python:3.0-python3.8-core-tools
> 
> Looks like only python3.8 core tools image is being published now
> https://github.com/Azure/azure-functions-docker/blob/dev/host/3.0/core-tools-publish.yml#L265

I can use 3.8 but I kind of need 3.9. I managed to compile it myself from the dockerfile posted in this repo with some minor modifications

**Comment by tleguijt** [comment]
Could this be reopened? Kinda still is an issue. I also need the python3.9 core tools.
It's listed here as available image https://github.com/Azure/azure-functions-docker#python but unable to pull this image.
