### ISSUE TITLE
What determines the installed version of Ruby on `azure-functions/python` image?

### ISSUE THREAD

**Issue by sshojiro** [Azure/azure-functions-docker#511]
I attempted to deploy my Dockerfile and Functions App in Python. I included `Gemfile` for Ruby dependency and I expected a docker image `mcr.microsoft.com/azure-functions/python:3.0-python3.7` to be Debian 10 or 11, whose default Ruby version is 2.5.2. But the following message showed up:

```commandprompt
> func azure functionapp publish myApp
Getting site publishing info...
Creating archive for current directory...
Performing remote build for functions project.
Deleting the old .python_packages directory
Could not find gozip for packaging. Using DotNetZip to package. This may cause problems preserving file permissions when using in a Linux based environment.
Uploading 289.83 MB [################################################]
Remote build in progress, please wait...
Updating submodules.
Preparing deployment for commit id '91b1f39398'.
Repository path is /tmp/zipdeploy/extracted
Running oryx build...
Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.7 -p packagedir=.python_packages/lib/site-packages
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20201015.1, Commit: xxxxxxxxxxxxxxxxxxxxxxxx, ReleaseTagName: 20201015.1

Build Operation ID: |xxxxxxxxxx
Repository Commit : xxxxxxxxx

Detecting platforms...
Detected following platforms:
  python: 3.7.9
  ruby: 2.7.2
```

My Dockerfile was like the below.

```Dockerfile
FROM mcr.microsoft.com/azure-functions/python:3.0-python3.7
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

# --- Build Python Environment ---
COPY requirements.txt /
RUN pip install -r /requirements.txt
COPY . /home/site/wwwroot

# --- Build Ruby Environment ---
RUN apt-get update && \
    apt-get install -y ruby-dev && \
    apt-get install -y poppler-utils && \
    apt-get install -y ruby-poppler
```

And my Gemfile (unused) has the below code:
```Gemfile
source "https://rubygems.org"
ruby "2.5.5" #"2.7.2"
gem "poppler"
```

Does anyone know what determines sub-language's version? This behaviour (maybe on Oryx) will impact my Functions App in future...
Thanks,

**Comment by balag0** [comment]
Those logs from publishing are from a different container which is using an image based on oryx and not mcr.microsoft.com/azure-functions/python:3.0-python3.7. The only purpose for that container is to support build and you wouldn't have control over that container to install additional dependencies. 

Did you need a specific ruby version available at runtime or build time?

**Comment by sshojiro** [comment]
Hi @balag0,
Thanks for the comment. Okay, the remote env is on Oryx and I don't have the control... No, I don't need a specific version of ruby this time. But the behaviour was slightly confusing, so I was little interested in what was right.
Thanks,

**Comment by sshojiro** [comment]
**Further Investigation Report**

This was an issue of deployment and destination OS (and subscription plan). 
[Ruby](https://github.com/microsoft/Oryx/blob/main/doc/runtimes/ruby.md#detect) is installed when `Gemfile` is located in the repo, while [Java](https://github.com/microsoft/Oryx/blob/main/doc/runtimes/java.md) is installed when `*.{java,jsp}` file(s) is found in the repo.

When you use `Azure Functions Core Tools CLI`, [Zip Deploy](https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies#zip-deploy) is a standard way of deployment. In such cases, Oryx, the destination OS, tries to detect platforms (=programming languages). We can help Oryx detect the right platforms by preparing specific types of files at the right location.
