### ISSUE TITLE
[V4 Images] Dotnet V4 Images use of linux-libc-dev have multiple vulnerabilities with fixes available

### ISSUE THREAD

**Issue by kevin-benton** [Azure/azure-functions-docker#521]
Affected Versions andTags:

* dotnet:4
* dotnet:4-slim
* dotnet-isolated:4
* dotnet-isolated:4-slim
* dotnet-isolated:4-dotnet-isolated6.0
* dotnet-isolated:4-dotnet-isolated6.0-slim

By running a `trivy` scan against any of these tags produces the same list of patchable vulnerabilities, 9 of them being ranked as HIGH importance. The scan I ran is `docker run --rm aquasec/trivy image --ignore-unfixed mcr.microsoft.com/azure-functions/$image:$tag` where the `$image` and `$tag` can be replaced with any above.

The patch is updating `linux-libc-dev` from `5.10.46-4` to `5.10.46-5`. I'm unsure if a simple rebuild of the images will fix the issue or version pinning is required.

I have created a patch base image for myself (content below) so this is not a high priority issue for me, but I wanted to post in case others have the same issue.

Patched Dockerfile (using `4-slim`; change to your preference):
```
FROM mcr.microsoft.com/azure-functions/dotnet:4-slim

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    FUNCTIONS_WORKER_RUNTIME=dotnet \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

RUN apt-get update && \
    apt-get install -y --no-install-recommends linux-libc-dev=5.10.46-5 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

CMD [ "/azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost" ]
```

**Comment by balag0** [comment]
Thanks for reporting this.
Yes, rebuilding the images should fix this. So this should be fixed as part of the next functions image release. (ETA 1-2 weeks)

**Comment by kevin-benton** [comment]
Great. I'll check again once I see the release.

**Comment by kevin-benton** [comment]
Closing as of Oct. 27, 2021 as vulnerabilities no longer exist.
