### ISSUE TITLE
Using windows container base image to run functions 

### ISSUE THREAD

**Issue by abhinav12** [Azure/azure-functions-docker#523]
Hi, 
I am trying to to host azure functions in docker using Windows containers. I am currently using mcr.microsoft.com/azure-functions/dotnet:3.0-nanoserver-1809. The function app uses v3 runtime and is implemented as a .netcoreapp3.1.

The container runs fine, but on accessing the http trigger locally, I am getting "function host is not running."  Need help in figuring out what I am missing. 

Docker Desktop Version : 4.1.0 on Windows10

Complete csproj : 
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.1.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

```

Complete docker file : 
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS installer-env 

COPY . /src/dotnet-function-app 
RUN cd /src/dotnet-function-app && \
    mkdir -p \home\site\wwwroot && \
    dotnet publish func.csproj --output \home\site\wwwroot

# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/dotnet:3.0-appservice
FROM mcr.microsoft.com/azure-functions/dotnet:3.0-nanoserver-1809
ENV AzureWebJobsScriptRoot=\home\site\wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]

ENV AzureWebJobsStorage="UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://host.docker.internal"
ENV FUNCTIONS_WORKER_RUNTIME="dotnet"
```
P.S. When I use the above app with the linux image mcr.microsoft.com/azure-functions/dotnet:3.0, it works. 

Repro steps : 
1. Use core tools (v3.0.3442) to create sample durable function with dotnet runtime with docker. 
2. Update docker file to the one provided (Need to change .csproj name )

**Comment by v-bbalaiagar** [comment]
Hi @abhinav12 , Apologies for the delayed response, We would like to know if you are still facing the same issue so that I can route this issue to concerned team.

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
