### ISSUE TITLE
Outdated pwsh version

### ISSUE THREAD

**Issue by PleaseStopAsking** [Azure/azure-functions-docker#530]
The powershell7-core-tools dockerfile has a hardcoded version var for installing pwsh. The current version is 7.0.3 which is 5 releases behind the current 7.0.x release tree. Is there a reason to leave this set to 7.0.3 or can we get this bumped to the latest release in the 7.0.x tree or even the latest 7.1.x release?

I can submit a PR if there are no technical limits.

Thanks,

https://github.com/Azure/azure-functions-docker/blob/9e6ddfd52a39f554886a808e4cddb9c3771d0f93/host/3.0/buster/amd64/powershell/powershell7-core-tools.Dockerfile#L14

**Comment by balag0** [comment]
Adding @Francisco-Gamino
