### ISSUE TITLE
Host v4 core-tools images installs azure-functions-core-tools-3

### ISSUE THREAD

**Issue by RiaanVR** [Azure/azure-functions-docker#566]
Hi, I'm getting started with a dev container and a new app and thought to use the latest image.

I'm using this base image mcr.microsoft.com/azure-functions/python:4-python3.9-core-tools, which I am to understand is this [DockerFile](https://github.com/Azure/azure-functions-docker/blob/dev/host/4/bullseye/amd64/python/python39/python39-core-tools.Dockerfile) 

However this does not install the SDK for v4 azure functions host, is this intentional or should it be considered a bug to resolve?

**Comment by pragnagopa** [comment]
Thanks for reporting. This is a bug.

**Comment by pragnagopa** [comment]
cc @fabiocav @balag0
