### ISSUE TITLE
Azure Functions V4 Linux support for NTLM

### ISSUE THREAD

**Issue by stevehawken** [Azure/azure-functions-docker#568]
#### Investigative information

Please provide the following:

- Timestamp: 2021-12-02 20:45:01.486
- Function App version: V4
- Invocation ID: b40ec635-67be-436b-9d5e-803abffc2f65
- NET: 6.0
- Region: East US

#### Repro steps

I am writing an Azure function that connects to a SharePoint 2016 farm (on prem) over SOAP which uses NTLM. It works fine on Windows but when I deploy it to Azure Functions V4 on Linux (using Code not Docker) instance I get the following error:

GSSAPI operation failed with error - An unsupported mechanism was requested. NTLM authentication requires the GSSAPI plugin 'gss-ntlmssp'.

From what I've read simply installing this package 'gss-ntlmssp' resolves the issue. Can this package be added to the runtime? At this point I'm not ready to run my own custom docker containers for Azure functions and also don't see any V4 images yet either.

#### Expected behavior

Functions runs and can utilize NTLM on Linux.

#### Actual behavior

Returns an error and does not run at all.

#### Known workarounds

Option 1: Run this on a Windows azure based functions host.

Option 2: (Maybe- have not tried) Run your own docker container in azure functions with gss-ntlmssp installed.

**Comment by pragnagopa** [comment]
As of now there are no plans  to install - `gss-ntlmssp` as part of runtime images. cc @balag0 @ahmelsayed for input.

 Please see https://github.com/Azure/azure-functions-docker/tree/dev/host/4 for V4 docker files - we will be updating readme with the right tags soon.

**Comment by stevehawken** [comment]
@v-bbalaiagar - This is a dedicated plan.

@pragnagopa - Thank you for the information. Is there a reasoning behind not including the package? I pay for a dedicated Linux app hosting plan and without that package I would need to purchase another plan under Windows just to run a single function that requires NTLM. 

I could use the free plan but we always use app service plans to provide dedicated predictable (always on) resources. My next step is to try and create my own Docker image with the package installed once the images are available.

**Comment by balag0** [comment]
@stevehawken Like you pointed out since this is a dedicated plan, you should still be able to build a custom image that installs all the required packages.
The reasoning is just keeping the image size/ maintenance cost smaller since the same image is being used by all apps of the same type and most of the other apps might not need this. It is also very difficult to remove a package once it has been added.
There is also less chances of dependencies breaking since you would have complete control over the versions.

**Comment by stevehawken** [comment]
This was resolved by creating my own docker container using the v4 image and adding gss-ntlmssp to it. For others running into the same issue you have the following options:

1. Create a custom docker container and add gss-ntlmssp
2. Run on windows
