### ISSUE TITLE
Publish V4 Core Tools Images

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-docker#578]
- Publish Core Tools images for all the supported languages
- Update readme to include right tags for V4 core tools images

**Comment by pragnagopa** [comment]
Also need to investigate why few core-tools images are using devcontainer as base image: https://github.com/Azure/azure-functions-docker/blob/dev/host/4/bullseye/amd64/python/python38/python38-core-tools.Dockerfile#L6 vs language sdk / runtime as base image: https://github.com/Azure/azure-functions-docker/blob/dev/host/4/bullseye/amd64/java/java8/java8-core-tools.Dockerfile#L6

We need to use a consistent approach

**Comment by pragnagopa** [comment]
@vrdmr  - is there any reason to use devcontainer as base image : https://github.com/Azure/azure-functions-docker/blob/dev/host/4/bullseye/amd64/python/python38/python38-core-tools.Dockerfile#L6 instead of `python:3.9-bullseye` similar to Java and dotnet core-tools images?

**Comment by TsuyoshiUshio** [comment]
I identify the issue by [the python 3.8 v4 core tools image fails to build](https://azure-functions.visualstudio.com/azure-functions-docker/_build/results?buildId=13113&view=logs&j=73f01dec-67da-5025-3a59-6c08056acec7&t=4ddcf9fa-0b3a-5aeb-e4cb-33d73590d36f). I suppose bullseye deb package might not published. 
Let me explain.  We search `/etc/apt/sources.list.d` directory and find the sources.  dotnet in-proc (success), java (success), python 3.8 (Unable to locate azure-functions-core-tools-4) Let's double check if apt publish the bullseye source. 

# Issue 

```
$ apt install azure-functions-core-tools-4
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package azure-functions-core-tools-4
```

## dotnet in-proc 
```bash
root@efa347042129:/etc/apt/sources.list.d# cat microsoft-prod.list 
deb [arch=amd64] https://packages.microsoft.com/debian/9/prod stretch main
```

## java8
```bash
root@46fb8774b408:/etc/apt/sources.list.d# cat dotnetdev.list 
deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-buster-prod buster main
```

## python3.8
```bash
root ➜ /etc/apt/sources.list.d $ cat dotnetdev.list 
deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-bullseye-prod bullseye main
```

# How to solve
We might have following solutions. Which one would you prefer? @anthonychu ?  or other suggestion is welcome. 

* Downgrade image from 11 to 10.
* Publish bullseye apt package for azure-functions-core-tools
* Install with npm

**Comment by pragnagopa** [comment]
cc @anthonychu

**Comment by pragnagopa** [comment]
@TsuyoshiUshio  - Java and dotnet core tools images should be using bullseye deb package as well?

**Comment by TsuyoshiUshio** [comment]
It looks core-tools not supported yet.  https://github.com/Azure/azure-functions-core-tools/issues/2702 
It is confusing since the Dockerfile is under bullseye. However, for dotnet and java and others might be decided not to go with bullseye. Let's check the context. @balag0  Do you know about it?

**Comment by TsuyoshiUshio** [comment]
It might be easier to move python/powershell image from `3.8` to `3.8-buster` 

https://github.com/microsoft/vscode-dev-containers/blob/main/containers/python-3/.devcontainer/base.Dockerfile#L1
https://github.com/Azure/azure-functions-docker/blob/dev/host/4/bullseye/amd64/python/python38/python38-core-tools.Dockerfile#L6

**Comment by TsuyoshiUshio** [comment]
Powershell using `dotnet/sdk:6.0.100`. We might use `6.0.100-focal` (Ubuntu 20.04) instead, if it is ok. It is supported. https://github.com/Azure/azure-functions-core-tools#ubuntu-2004

https://mcr.microsoft.com/v2/dotnet/sdk/tags/list
https://github.com/Azure/azure-functions-docker/blob/dev/host/4/bullseye/amd64/powershell/powershell7-core-tools.Dockerfile#L1

**Comment by RiaanVR** [comment]
@pragnagopa Did you see that the packages are now available for bullseye as well [see ](https://github.com/Azure/azure-functions-core-tools/issues/2702#issuecomment-995299397)

**Comment by pragnagopa** [comment]
@RiaanVR - We are working on publishing images. Should be avaialble soon.

**Comment by TsuyoshiUshio** [comment]
I'm working on it on the PR. All of them becomes bullseye. However, Java base image doesn't support bullseye, so that we are stop publishing the java. I created an issue. https://github.com/Azure/azure-functions-core-tools/issues/2878 
Once Java base image available, I'll update the pipeline and publish it.
