### ISSUE TITLE
Upgrade v4 host dotnet sdk runtime image from preview to release

### ISSUE THREAD

**Issue by runtimeware** [Azure/azure-functions-docker#585]
v4 host still references the preview (https://github.com/Azure/azure-functions-docker/blob/dev/host/4/bullseye/amd64/dotnet/dotnet-isolated/dotnet-isolated.Dockerfile#:~:text=FROM%20mcr.microsoft.com/dotnet/sdk%3A6.0.100%2Drc.2%20AS%20runtime%2Dimage) version of the sdk - are there plans to get on the released version?

Production functions deployed w/ the v4 runtime are listing the RC image in log streams - this is generally confusing since the sdk and other services are GA.

**Comment by v-bbalaiagar** [comment]
Tagging @pragnagopa / @balag0  ,  for more insights

**Comment by CooperLink** [comment]
Thank you for making us aware of this.  We are rolling out a new version (v4.1.1) that will no longer log the RC image in log streams. Images that we use by default in production are defined using -composite.template files such as https://github.com/Azure/azure-functions-docker/blob/dev/host/4/bullseye/amd64/dotnet/dotnet-isolated/dotnet-isolated-composite.template#L4 

When the current release is rolled out to your application, it will no longer report rc image runtimes.

**Comment by runtimeware** [comment]
Sounds great thanks for following up

**Comment by CooperLink** [comment]
The above removes nightly from non-production images.  You should still receive the fix as the release rolls out.  :)
