### ISSUE TITLE
Remove references to nightly images

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-docker#591]
Still using `nightly` in quite a few places: https://github.com/Azure/azure-functions-docker/search?l=Dockerfile&q=nightly

**Comment by kshyju** [comment]
> Still using `nightly` in quite a few places: https://github.com/Azure/azure-functions-docker/search?l=Dockerfile&q=nightly

@CooperLink FYI. Are all of these the old/obsolete files?

**Comment by CooperLink** [comment]
Powershell 7 v4 is the only blessed production image that references 'nightly'.  For now I will introduce a PR to remove all references to nightly and test the images.  Should be fine to just move them all over to GA dotnet6.

To be clear, non-appservice images are not necessarily old/obsolete.  They do have purposes.  They are just not used in production Linux Dedicated Applications for Azure Functions.

**Comment by CooperLink** [comment]
Merged resolution to this issue. Thank you for filing @anthonychu
