### ISSUE TITLE
Regression in azure-functions/dotnet-isolated:4 Docker image

### ISSUE THREAD

**Issue by esimkowitz** [Azure/azure-functions-docker#600]
Hello, I am seeing a regression in the dotnet-isolated:4 Docker image. A few months ago, trying to run an Azure Function that was built inside this image resulted in the following error:
```
info: Host.Function.Console[0]
      It was not possible to find any compatible framework version
info: Host.Function.Console[0]
      The framework 'Microsoft.AspNetCore.App', version '6.0.0' (x64) was not found.
info: Host.Function.Console[0]
        - No frameworks were found.
 ```
which manifested as a 500 error when trying to invoke a function and the following exception in the Function runtime:
```
Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker[0]
      Final functionDispatcher state: WorkerProcessRestarting. Initialization timed out and host is shutting down
fail: Function.Function1[3]
      Executed 'Functions.Function1'
```

I haven't seen this issue for a while but this week I have noticed it cropping up again. The workaround I have (which I modified from this issue: #441) is to add the following lines to my Dockerfile:
```Dockerfile
RUN apt-get update -y \
  && apt-get install -y apt-transport-https wget \
  && wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
  && dpkg -i packages-microsoft-prod.deb \
  && apt-get update -y \
  && apt-get install -y aspnetcore-runtime-6.0
```

This seems like a regression in your Docker image. Do you not package the ASP.NET Core 6.0 runtime into the Docker image?

**Comment by kshyju** [comment]
The `Microsoft.AspNetCore.App` runtime was not included in the Linux images.  This was fixed in this PR: https://github.com/Azure/azure-functions-docker/pull/562. Rolling out this change is still in-progress. Will update this thread when it is done.

@VpOfEngineering FYI

**Comment by cgillum** [comment]
Just chiming in that I ran into the same issue today. Thankfully, the workaround provided by @esimkowitz works for me too. 👍🏽

**Comment by esimkowitz** [comment]
@kshyju @VpOfEngineering do you have any updates/ETAs on the rollout of the new Docker image version for azure-functions/dotnet-isolated:4?

**Comment by VpOfEngineering** [comment]
We are currently in-progress to roll out the changes. Within the next week, you should see version 4.1.3 appear which includes the new image.

**Comment by VpOfEngineering** [comment]
I will also post an update here when it is fully deployed

**Comment by esimkowitz** [comment]
@kshyju @VpOfEngineering I just tried out 4.1.3 as the base image and it is still failing with the same error. @cgillum can you give it a try too? I used mcr.microsoft.com/azure-functions/dotnet-isolated:4.1.3

**Comment by CooperLink** [comment]
Hi Evan, thank you for filing this important issue. I can see what is happening here. The changes that @kshyju introduced in #562 are available in the -appservice images provided by the Functions team.  Those changes were not included in the non-appservice images that you are using.  For now, you can build based on 4.1.3-appservice tag and you should be unblocked. Sorry about this. Will be taking steps to avoid these problems in the future and will be including aspnet in our next release of the images.

**Comment by esimkowitz** [comment]
@CooperLink any update on the PR to get this change into all feeds? I see it's been open for 2 weeks

**Comment by esimkowitz** [comment]
@CooperLink I see that the PR has been merged. Do you know when I can expect it to roll out to the dotnet-isolated:4 feed?

**Comment by CooperLink** [comment]
Hi @esimkowitz the rollout for dotnet-isolated:4 will be completed in the next release 4.2.0.  That release process should begin this week.  The image will be available at dotnet-isolated:4 about 1 week after that.  Expected ETA is within one month. For the time being you can use AppService images as mentioned. Sorry for the delay

**Comment by esimkowitz** [comment]
I've tested this using the dotnet-isolated:4 image and everything looks good, I think we can close this issue
