### ISSUE TITLE
Node images are missing dependencies for Playwright

### ISSUE THREAD

**Issue by CooperLink** [Azure/azure-functions-docker#614]
For Premium customers, Consumption Images support playwright but, the same app fails on premium workers because of a bad dependency.  Need to include the dependency here.

**Comment by johnayoub** [comment]
@pragnagopa @CooperLink any update on this? We are currently being blocked to upgrading to V4 because of the missing dependencies. This is becoming a critical issue for us? Any reason the dependencies were removed from V4?

**Comment by yuna-s** [comment]
Hi @CooperLink Hope Hope you are doing well. Could you give me any updates if playwight supports in EP plan? thank you

**Comment by CooperLink** [comment]
Hi @yuna-s this has been completed, The node images should support playwright. I checked the node18 image below

https://github.com/Azure/azure-functions-docker/blob/dev/host/4/bullseye/amd64/node/node18/node18-composite.template#L12
