### ISSUE TITLE
Move dotnet-isolated images off of .NET 5

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-docker#623]
With support for .NET 5 going out-of-support soon, we should be moving our dotnet-isolated images to .NET 6

For example: https://github.com/Azure/azure-functions-docker/blob/dev/host/3.0/buster/amd64/dotnet/dotnet-isolated/dotnet-isolated-composite.template#L4

**Comment by liliankasem** [comment]
Moving to sprint as this is due in 3 months

**Comment by kshyju** [comment]
May 08, 2022 is the **End of support** date for .NET 5.

**Comment by fabiocav** [comment]
Closing this as we won't move V3 images to support .NET 6. The guidance for .NET 6 is to move to V4 and we want to avoid bringing .NET 6 workloads to V3.

/cc @paulbatum
