### ISSUE TITLE
Unable to build docker compose with Azure Function project in Visual Studio 2022

### ISSUE THREAD

**Issue by 7amou3** [Azure/azure-functions-docker#631]
I'm trying to add an Azure Function project to a docker-compose file created in Visual Studio 2022 but this causes the solution to fail to build
(Docker for Windows 4.5.1 (74721), with WSL2 support enabled, running in Linux container mode on Windows 11 Pro)

Steps to reproduce:
1. Create a new solution with a Web Api project 'Web' that includes docker support.
1. Add a new Azure Function project 'Func' with an Http trigger function and then added docker support via Visual Studio Add > Docker Support option.
1. Add 'Container Orchestration Support' to Web project to generate a docker-compose.yml file that has the web app

At this point the solution builds debugging works for the web or func app in docker or docker-compose - all good.

When 'Func' project is added manually to docker-compose.yml the solution no longer builds
However, I can run docker-compose fine from the command line:
`docker-compose -f docker-compose.yml up
`
and both Web and Func app start up fine.

My docker-compose.yml file is
```version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: Web/Dockerfile

  func:
    image: ${DOCKER_REGISTRY-}func
    build:
      context: .
      dockerfile: Func/Dockerfile
```

Any ideas why I get the above error when building the solution in Visual Studio?

**Comment by v-bbalaiagar** [comment]
Hi @7amou3 , Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by tomas-blanarik-visma** [comment]
I have the same issue, any progress on this?

**Comment by v-bbalaiagar** [comment]
Hi @pragnagopa / @balag0  , Could you please look into this issue

**Comment by pragnagopa** [comment]
Thanks for reporting the issue.

>  However, I can run docker-compose fine from the command line:

This appears to be issue with the tooling.

@vijayrkn - do you have a point of contact to help us figure out next steps for this issue?

cc @CooperLink

**Comment by vijayrkn** [comment]
Adding @ravipal from the Container tooling side.

**Comment by ravipal** [comment]
@7amou3 & @tomas-blanarik what is your VS version? The docker compose support for Azure Functions is added in 17.2 Preview 2. You should be able to add Container Orchestration support for your Func project in the supported VS version.

**Comment by pragnagopa** [comment]
@vijayrkn  / @ravipal - thank you for prompt follow up here! Is there a github repo we can transfer this issue to?

**Comment by ravipal** [comment]
You may transfer this issue to https://github.com/microsoft/DockerTools.

**Comment by pragnagopa** [comment]
New issue tracked here - https://github.com/microsoft/DockerTools/issues/334
