### ISSUE TITLE
DSA-5073 and DSA-5085 Impacting Docker Images

### ISSUE THREAD

**Issue by wsugarman** [Azure/azure-functions-docker#633]
My team noticed that the base docker image `azure-functions:4@sha256:4237bd12a9e8df217009cbfd5a809a5a7e38ad28bb1556ccc929094e54d392bc` contains a vulnerable version of `libexpat1` as flagged by [DSA-5073](https://www.debian.org/security/2022/dsa-5073) and [DSA-5085](https://www.debian.org/security/2022/dsa-5085).

Executing `dpkg -l` shows it contains `libexpat1:amd64` at version `2.2.10-2`. If my reading of the issues is correct, at least version `2.2.10-2+deb11u2` should be used.

**Comment by balag0** [comment]
Thanks for reporting. Do you happen to have the image:tag being used?

**Comment by balag0** [comment]
Potentially same issue as https://github.com/Azure/azure-functions-docker/issues/613

**Comment by wsugarman** [comment]
I noticed it in our usage of `mcr.microsoft.com/azure-functions/dotnet:4.0.1.16816@sha256:2c18c4ca6ad982257e9023161329c38be6d9d494bc48a6aae15ef43cc8f7ea5d`, but I moved to the latest SHA for tag 4 and still see it. So, at the very least the issue is found in:

- `mcr.microsoft.com/azure-functions/dotnet:4@sha256:4237bd12a9e8df217009cbfd5a809a5a7e38ad28bb1556ccc929094e54d392bc`
- `mcr.microsoft.com/azure-functions/dotnet:4-slim@sha256:4237bd12a9e8df217009cbfd5a809a5a7e38ad28bb1556ccc929094e54d392bc`
- `mcr.microsoft.com/azure-functions/dotnet:4.1.3@sha256:4237bd12a9e8df217009cbfd5a809a5a7e38ad28bb1556ccc929094e54d392bc`
- `mcr.microsoft.com/azure-functions/dotnet:4.1.3-slim@sha256:4237bd12a9e8df217009cbfd5a809a5a7e38ad28bb1556ccc929094e54d392bc`
