### ISSUE TITLE
Dotnet: Container does not stop when Kubernetes sends SIGTERM

### ISSUE THREAD

**Issue by PehrGit** [Azure/azure-functions-docker#677]
We've noticed that our function container does not terminate when Kubernetes tells it to stop. Instead, nothing happens until the "TerminationGracePeriodSeconds" have elapsed and the container is SIGKILLed. 

This could be when a new pod is available and the old one can be terminated, but is especially problematic when we scale up to 100 instances with KEDA and then down to 0 instances. We have some long running functions so we cannot set our TerminationGracePeriodSeconds too low, otherwise the function will be killed halfway through its run.

So we set TerminationGracePeriodSeconds to 180 seconds to allow the running invocations to finish, but this means in practice that pods which are no longer needed, will remain in "terminating" state for 180 seconds before they are finally killed. 

This can also be reproduced locally by running in Docker and sending `docker stop --time 30 <containername>`. The container keeps running for 30 seconds until it is killed.

We are using `mcr.microsoft.com/azure-functions/dotnet:4`

**Comment by balag0** [comment]
Yes, this is a limitation on the current images. Is using a custom image based on published functions images an option?

**Comment by PehrGit** [comment]
> Yes, this is a limitation on the current images. Is using a custom image based on published functions images an option?

Ah good to hear that we're not crazy and it is indeed a limitation. Yes, using custom images would certainly be an option, do tell me more :)

**Comment by PehrGit** [comment]
@balag0 Hi, just checking to see if you received my previous comment. Can you tell me more about using a custom image to fix this issue?

**Comment by balag0** [comment]
I think we would need the following
1)a way to handle sigterm (checkout https://github.com/Azure/azure-functions-docker/issues/404)
2)the sigterm handler to start a polling task that checks if the container is busy 
3)the polling task will exit the container once the container is found to be idle
4) if the container remains busy  it will be killed eventually due to sigkill.

What might be missing is an api you can use to check the container status in step (2). if you have an alternative way to check status then the above approach could work until the images implement this solution by default.

**Comment by PehrGit** [comment]
As mentioned in #404, the following seems to work:

```shell
#!/usr/bin/env bash

export DOTNET_USE_POLLING_FILE_WATCHER=true

if [ -z $PORT ]; then
  export ASPNETCORE_URLS=http://*:80
else
  export ASPNETCORE_URLS=http://*:$PORT
fi

if [ -z $SSH_PORT ]; then
  export SSH_PORT=2222
fi

if [ "$APPSVC_REMOTE_DEBUGGING" == "TRUE" ]; then
    export languageWorkers__node__arguments="--inspect=0.0.0.0:$APPSVC_TUNNEL_PORT"
    export languageWorkers__python__arguments="-m ptvsd --host localhost --port $APPSVC_TUNNEL_PORT"
fi

sed -i "s/SSH_PORT/$SSH_PORT/g" /etc/ssh/sshd_config

service ssh start

# run background
if [ -f /azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost ]; then
    { setsid /azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost; } &
else
    { setsid dotnet /azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost.dll; }  &
fi

subshell_pid=$!

function trapSigTerm()
{
  pids=$(ps -ax -o ppid,pid --no-headers |
      sed -r 's/^ +//g;s/ +/ /g' |
      grep "^$subshell_pid " | cut -f 2 -d " ");
  for child in $pids;  do
    echo kill -SIGINT "-$child" && kill -SIGINT "-$child"
  done
  wait $subshell_pid
}

trap trapSigTerm SIGINT SIGTERM

# wait
wait
```

With the addition of the following in the Dockerfile:

```dockerfile
RUN apt-get install procps -y
```


**1)a way to handle sigterm (checkout #404)** 
See 2
**2)the sigterm handler to start a polling task that checks if the container is busy** 
This handles the SIGTERM and passes a SIGINT to the host, initiating the graceful shutdown. No need to check if the container is busy, the function host will handle it's own graceful shutdown.
**3)the polling task will exit the container once the container is found to be idle** 
The "wait" in the script waits until the process shuts down.
**4) if the container remains busy it will be killed eventually due to sigkill.**
Yep

I tested this with an HTTP trigger that runs for 12 seconds. If I send the "docker stop" command while no function is running, it logs 

> Stopping JobHost                                                                    
> Stopping the listener 'Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBlListener' for function 'SynchronizeAccountsFunction'                               
> Host.Startup[0]                                                                     
> Stopped the listener 'Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBindingProvider+HttpTriggerBinding+NullListener' for function 'TestFunction'
> Stopped the listener 'Microsoft.Azure.WebJobs.Extensions.Http.HttpTriggerAttributeBindingProvider+HttpTriggerBinding+NullListener' for function 'TestFunction'                                                                  
> Job host stopped                

And when I stop the docker container while an invocation to the HTTP trigger is in progress, the host delays shutting down  for about 5 seconds, not accepting new invocations, and then shuts down, after which the container also exits. Yay! That's what we were after!

Now we just need to figure out how to increase that 5 seconds timeout so that our long running functions have a chance to finish. Is there something we can configure in the Startup to increase that timeout?

**Comment by CooperLink** [comment]
You can set the environment variable "FUNCTIONS_ENABLE_DRAIN_ON_APP_STOPPING" to "true" in your custom docker image.  That should enable drain mode for your containers as long as your Kubernetes Service Host is also defined.  Drain mode will cause your containers to allow 10 minutes for execution rather than 5 seconds. Hopefully this is long enough for your use case.  Please let us know if this works for you.

Here is the commit that enabled drain mode in the host for more context : https://github.com/Azure/azure-functions-host/commit/a68bf2ea2b5722a2e656d8fe6fec2fa25b4a8990

**Comment by PehrGit** [comment]
> You can set the environment variable "FUNCTIONS_ENABLE_DRAIN_ON_APP_STOPPING" to "true" in your custom docker image. That should enable drain mode for your containers as long as your Kubernetes Service Host is also defined. Drain mode will cause your containers to allow 10 minutes for execution rather than 5 seconds. Hopefully this is long enough for your use case. Please let us know if this works for you.
> 
> Here is the commit that enabled drain mode in the host for more context : [Azure/azure-functions-host@a68bf2e](https://github.com/Azure/azure-functions-host/commit/a68bf2ea2b5722a2e656d8fe6fec2fa25b4a8990)

Thanks @CooperLink for that suggestion. I tried it out and it does indeed allow the host to keep running until the invocations are complete. However, after the invocations are complete, it will keep running for the full 10 minutes if not forcibly shut down. So basically the problem described in https://github.com/Azure/azure-functions-host/issues/7188#issuecomment-789025291.

It looks like that problem is on the roadmap but has not been tackled yet?

Looking on another axis, is there something we can do in our C# code to delay the shutdown? I know that in ASP.NET Core API's we can register a method on `IHostApplicationLifetime.ApplicationStopping` and block shutdown until some task is finished. I tried that out in dotnet-isolated functions and it seems that we can indeed delay the shutdown.
```csharp
       var logger = host.Services.GetRequiredService<ILogger<Program>>();
        var applicationLifetime = host.Services.GetRequiredService<IHostApplicationLifetime>();

        // Ensure graceful shutdown
        applicationLifetime.ApplicationStopping.Register(() => ApplicationStopping(logger));

        await host.RunAsync();
    }

    private static void ApplicationStopping(ILogger<Program> logger)
    {

        var j = 20;
        for (int i = 0; i < j; i++)
        {
             // TODO: what to check here?
            logger.LogInformation($"Sleeping {i}/{j}");
            Thread.Sleep(1000);
        }
    }
```

But now we need some way to determine if any functions are still running, to know if we can shutdown yet or not. I noticed this PR https://github.com/Azure/azure-webjobs-sdk/pull/2775 introduces an API for that but can we access the FunctionExecutor in client code or is that only available within the host?

**Comment by PehrGit** [comment]
@CooperLink @balag0 I noticed this issue was closed: https://github.com/Azure/azure-functions-host/issues/2308, does that mean that this issue should be fixed now? Our pods don't seem to be responding to SIGTEM yet, is that because the docker image is not up to date with the latest functions-host version, or are these unrelated issues?

**Comment by MO2k4** [comment]
@PehrGit thank you so much for your script 🫡

i finally got it working, the trick is that you need to add the cancellation token to your function trigger like so:

```cs
public static async Task Run(
        [EventHubTrigger("hub-name", Connection = "connectionString")]
        EventData[] events,
        CancellationToken cancellationToken)
```

This way a OperationCanceledException will be thrown, which leads to a shutdown and drain inside the webjobs host :-)

I validated this for eventhub trigger, with the debug output => There it was host shutdown!

> Call to StopAsync complete, registered listeners are now stopped

Finally i got to a resilient state 🤘

**Comment by PehrGit** [comment]
It took a while but we finally have a complete solution. Previously we had accomplished that the container would at least respond to a SIGTERM signal and enter drain mode, but we still had the issue that the host would not actually shut down and the container would keep running for as long as Docker/Kubernetes would allow it. 

We were still missing points 2 to 4 from this list:
> I think we would need the following 1)a way to handle sigterm (checkout #404) 2)the sigterm handler to start a polling task that checks if the container is busy 3)the polling task will exit the container once the container is found to be idle 4) if the container remains busy it will be killed eventually due to sigkill.
> 
> What might be missing is an api you can use to check the container status in step (2). if you have an alternative way to check status then the above approach could work until the images implement this solution by default.

But that API does exist! /admin/host/drain/status provides just what we need. So I've expanded the script to poll that endpoint and wait for the drain status to be Completed. Now we have complete solution that enables true graceful shutdown.

Updated script below:
```sh
#!/usr/bin/env bash

export DOTNET_USE_POLLING_FILE_WATCHER=true

if [ -z $PORT ]; then
  export ASPNETCORE_URLS=http://*:80
else
  export ASPNETCORE_URLS=http://*:$PORT
fi

if [ -z $SSH_PORT ]; then
  export SSH_PORT=2222
fi

if [ "$APPSVC_REMOTE_DEBUGGING" == "TRUE" ]; then
    export languageWorkers__node__arguments="--inspect=0.0.0.0:$APPSVC_TUNNEL_PORT"
    export languageWorkers__python__arguments="-m ptvsd --host localhost --port $APPSVC_TUNNEL_PORT"
fi

sed -i "s/SSH_PORT/$SSH_PORT/g" /etc/ssh/sshd_config

service ssh start

# run background
if [ -f /azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost ]; then
    { setsid /azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost; } &
else
    { setsid dotnet /azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost.dll; }  &
fi

# get the process id of the background process we just started
subshell_pid=$!

function trapSigTerm()
{
  pids=$(ps -ax -o ppid,pid --no-headers |
      sed -r 's/^ +//g;s/ +/ /g' |
      grep "^$subshell_pid " | cut -f 2 -d " ");
  for child in $pids;  do
    echo kill -SIGINT "-$child" && kill -SIGINT "-$child"
  done

  state=$(curl -s localhost/admin/host/drain/status | jq --raw-output '.state'); 
  outstandingInvocations=$(curl -s localhost/admin/host/drain/status | jq --raw-output '.outstandingInvocations');
  
  while [ $state != Completed ];  do 
    echo "Draining state: '$state', Outstanding Invocations='$outstandingInvocations', waiting"; 
    
    sleep 2; 
    echo "slept, checking again"; 

    state=$(curl -s localhost/admin/host/drain/status | jq --raw-output '.state'); 
    outstandingInvocations=$(curl -s localhost/admin/host/drain/status | jq --raw-output '.outstandingInvocations'); 
  done; 
  
  echo "Draining state: '$state', Outstanding Invocations='$outstandingInvocations', Drain complete"
}

trap trapSigTerm SIGINT SIGTERM

# wait
wait
```

A few notes:
- Make sure that these environment variables are set, or the endpoint will require authentication:
  - WEBSITE_SITE_NAME
  - WEBSITE_INSTANCE_ID
- Make sure curl and jq are installed
- There's still a hardcoded 10 minute max to the graceful shutdown, see this issue: https://github.com/Azure/azure-functions-host/issues/8681
