### ISSUE TITLE
Vulnerabilities identified in dotnet:4-slim base image

### ISSUE THREAD

**Issue by frayeddev** [Azure/azure-functions-docker#684]
Hi, Our Snyk vulnerability scanner has detected a number of critical and high severity vulnerabilities coming from the latest version of the mcr.microsoft.com/azure-functions/dotnet:4-slim base image.

They are being picked up in the following packages and I've provided links to the issues.

glibc
gmp
openssl
zlib 

https://security.snyk.io/vuln/SNYK-DEBIAN11-GLIBC-2340922
https://security.snyk.io/vuln/SNYK-DEBIAN11-GLIBC-2340908
https://security.snyk.io/vuln/SNYK-DEBIAN11-GLIBC-1296898
https://security.snyk.io/vuln/SNYK-DEBIAN11-GLIBC-1911968
https://security.snyk.io/vuln/SNYK-DEBIAN11-GMP-1920938
https://security.snyk.io/vuln/SNYK-DEBIAN11-OPENSSL-2426309
https://security.snyk.io/vuln/SNYK-DEBIAN11-ZLIB-2433933

I didn't know if these are something I should raise here and if they can be addressed in the base image?

Thanks

**Comment by asos-bryanharveysmith** [comment]
I'm hopeful that the new release will solve the issue now that it's moved to the latest dotnet base image: https://github.com/Azure/azure-functions-docker/releases/tag/4.5.0

**Comment by pragnagopa** [comment]
Thanks for reporting.  We expect PR https://github.com/Azure/azure-functions-docker/pull/686 which is part of 4.5.0 will solve the issue
