### ISSUE TITLE
4-dotnet6-appservice image tag points to v4.3.2, not v4.5.2 

### ISSUE THREAD

**Issue by wg-davegriffiths** [Azure/azure-functions-docker#701]
Please can you remove `4-dotnet6-appservice` tag or update it to point to the latest image?  It still currently seems to point to v4.3.2 image, not the real latest (v4.5.2 at time of writing).  We followed online documentation to use this image tag, and left us with several months of vulnerabilities in the image.

**Comment by benbhall** [comment]
You beat me to it. Was just going to ask why we are not using floating tags e.g. 4.5 and 4 to the latest image when we [publish](https://github.com/Azure/azure-functions-docker/blob/dev/host/4/publish.yml). 

Like: https://github.com/dotnet/dotnet-docker/blob/2cca5dab1fa9f48c9cf621ff9201a625dc3f3a8a/documentation/supported-tags.md

**Comment by pragnagopa** [comment]
Functions Runtime 4.5.2 image that have latest dotnet SDK have been released. Above tags updated.
