### ISSUE TITLE
Create ssh enabled images for use in AppService

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-docker#74]
The changes needed for .Net are 
https://github.com/Azure/azure-functions-docker/commit/c6beee8c5a38bd3f1d44390a6bb6de72864f5d34

(For node we might need to launch the node process in debug mode additionally)

We will need to have separate ssh enabled images ( dotnet , node , python to begin with) to avoid security issue with having public username/password in the dockerfile. When used in appservice this is ok since the port is only exposed through kudu which requires auth.

The images will be named with -xdebug as part of their name (Ex: appsvc/php:5.6.38-apache-xdebug_1810291954). When remote debugging is enabled on a site , LWAS will pick the -xdebug image instead of regular image.

Matching launch.json config to use with vs code

{
            "name": ".NET Core SSH Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickRemoteProcess}",
            "pipeTransport": {
                "pipeProgram": "ssh",
                "pipeArgs": [ "-T", "root@127.0.0.1", "-p", "PORT_NUMBER", "-i", "PATH_TO_SSHPRIVATEKEY" ],
                "debuggerPath": "/root/vsdbg/vsdbg",
                "pipeCwd": "${workspaceRoot}",
                "quoteArgs": true
            }
        }
debugger path is preset based on dockerfile debugger installation location.
PORT_NUMBER is from
az webapp remote-connection create -g RESOURCE_GROUP -n APP_NAME -p PORT_NUMBER

**Comment by ahmelsayed** [comment]
a couple of questions Bala.

This debugger is just the dotnet debugger, correct? Is there a different configuration for node and python?

The bit about xdebug is only for php, right? so we don't have to do that since we don't have php image.

**Comment by balag0** [comment]
Correct. This is just for dotnet. Haven't investigated what debugger we need for python and node.cc @dariagrigoriu  
For now it would be good to have the basic dockerfiles structure created for all languages and we can add the required debuggers into the right dockerfile whenever we identify them.

The idea is that even in appservice we won't always use the (debugger installed, ssh enabled) images automatically. The right image will be picked by LWAS depending on the value of remotedebugging in the site config. (this is another pending workitem). The logic is based on whether or not the image name includes xdebug. This is what happens with php blessed images on app service right now.
Until we complete the LWAS piece of work, customers can modify LinuxFxVersion manually with the xdebug images after enabling remotedebugging.
