### ISSUE TITLE
Functions v1 image

### ISSUE THREAD

**Issue by NickDarvey** [Azure/azure-functions-docker#8]
I've seen references to Functions v1 being run inside a container,

>In this version we added support for:
>Functions v1 (.NET Framework) running in Windows Server Core container
https://github.com/Azure/Azure-Functions/issues/288#issuecomment-349810314

is there any chance that Dockerfile can be added to that repo and/or that image could be published so we can use it as part of our test environment for our v1 Functions till v2 is out of preview?

**Comment by ahmelsayed** [comment]
@jvano Do you have a v1 Dockerfile we can share with @NickDarvey ?

**Comment by jvano** [comment]
@NickDarvey , the containers that are used for "Azure Functions Runtime" preview 2 are designed to work just for the our On-premises scenario and there is no dockerfile in a shareable form at this point.

However, you can derive from the base images which are available here:
https://hub.docker.com/r/azfuncrun/azure-functions-runtime

We have two tags, one for v1 and other for v2.

**Note: Remember that this is a preview product and it is not recommended or supported for any production workload**

**Comment by NickDarvey** [comment]
Thanks for your response @jvano. I have some follow-ups:

**Clarification on naming**
Is Azure Functions Runtime preview 2 a release that contains both Azure Functions Runtime v1 and v2?

>the containers that are used for "Azure Functions Runtime" preview 2 are designed to work just for the our On-premises scenario and there is no dockerfile in a shareable form at this point
If this is designed to run on-premise, does that mean you have published the images (not the dockerfile) then? Where are those for v1?

>However, you can derive from the base images which are available here:
>https://hub.docker.com/r/azfuncrun/azure-functions-runtime
>
>We have two tags, one for v1 and other for v2.
Is the tag for v1, 'preview2-latest-servercore'?

**Comment by jvano** [comment]
In "Azure Functions Runtime" preview 2, the following two options are displayed:

- Option 1: "Functions v1 (.NET Framework) running in Windows Server Core container" which uses the docker hub image "azfuncrun/azure-functions-runtime:preview2-latest-servercore"
- Option 2: "Functions v2 (.NET Standard) running in Windows Nano Server container" which uses the docker hub image "azfuncrun/azure-functions-runtime:preview2-latest-nanoserver"
