### ISSUE TITLE
Latest docker image node:4-node16 causing startup issues binding type(s) 'queueTrigger' were not found

### ISSUE THREAD

**Issue by skibish** [Azure/azure-functions-docker#807]
Seems like in the latest docker build something was changed.

We started to receive the error message during the startup:

```
The '***' function is in error: The biding type(s) 'queueTrigger' were not found in the configured extension bundle. [..]
```

`node:4.13.0-node16` works as expected. `node:4.14.0-node16` is failing.

host.json
```json
{
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
   "version": "[3.3.0, 4.0.0)"
  }
}
```

They only thing we did was docker image rebuild.

Looks similar to #806

What should be reconfigured?

**Comment by thomas-lamure** [comment]
Exactly the same problem here

**Comment by austinheinrichs** [comment]
We are also seeing this same issue with the node:4-node14 image tag.  We pinned to node:4.13.0-node14 as well so that our serviceBusTrigger bindings would register.

**Comment by pragnagopa** [comment]
Thanks for reporting. We are investigating issue. cc @soninaren @CooperLink

**Comment by CooperLink** [comment]
Hi @skibish thanks for filing this issue. Could you please provide some more information about how you are deploying your Function Apps? Are you building your Function App code into the dockerfile? I have a local repro of your issue from a Custom Container Function App like what's described here : https://learn.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image?tabs=in-process%2Cbash%2Cazure-cli&pivots=programming-language-typescript#build-the-container-image-and-test-locally

On the other hand, we have found that deploying from zip or from VSCode does not reproduce the issue.  Are you using a custom container currently?

**Comment by skibish** [comment]
Hi @CooperLink ,

Sure. Thanks for looking into this one!

We are building custom docker image based on `mcr.microsoft.com/azure-functions/node:4-node16`.

**Comment by xinsnake** [comment]
I am able to provide a Dockerfile that has this problem:

```
FROM mcr.microsoft.com/azure-functions/node:4-node16

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY . /home/site/wwwroot

RUN cd /home/site/wwwroot && \
    npm run lint && \
    npm run build
```

Also the host.json file:

```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.3.0, 4.0.0)"
  }
}

```

Running `func start` locally does not have any problem.

**Comment by CooperLink** [comment]
Thank you for the information y'all. I am happy to report that we have remedied this issue with a new Function Docker image release. If you change your base image target to the version `4.14.0.3` you will receive a base image that includes the /bin directory for the extension bundles. I just verified that the node image you mentioned above has shipped with the fix at the node:4.14.0.3-node16.  That should fix this issue for you, but please let me know if I can further assist you. 

Tomorrow we will update the major version images such as ...python:**4**-python3.9 as well. I will keep this issue open until we have completed that major version deployment.

**Comment by skibish** [comment]
Confirming everything is back to normal with `4.14.0.3`

**Comment by pragnagopa** [comment]
Dup of https://github.com/Azure/azure-functions-docker/issues/806
