### ISSUE TITLE
mysqldump on Python

### ISSUE THREAD

**Issue by ayelencasamassa** [Azure/azure-functions-docker#833]
Greetings.
I have been dealing with this for a while.
Which version of python images should I use in order to be allowed to install mysql-client tools.
To be more specific, I need to have mysqldump binary.
Thanks.

**Comment by CooperLink** [comment]
Thank you for filing. I cannot comment on that specific dependency. But, the preferred Python docker image would be a v4 image of whatever runtime you are planning to use. There are dockerfile artifacts available here : https://github.com/Azure/azure-functions-docker/releases/tag/4.15.0

If you need to include an additional dependency to enable MySql you can use the documentation guide here : 
https://learn.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image
