### ISSUE TITLE
Yarn GPG key expired

### ISSUE THREAD

**Issue by justinh-kairos** [Azure/azure-functions-docker#842]
When attempting to use this image as part of a dev container with docker outside of docker feature enabled, the container fails to build because the Yarn GPG key is expired:
```GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>```

Please update the image with the new key

**Comment by ykgw-liuxin** [comment]
the same

**Comment by justinh-kairos** [comment]
For reference, the image I was attempting to use was ```mcr.microsoft.com/azure-functions/python:4-python3.9-core-tools```

**Comment by justinh-kairos** [comment]
When can I expect this to be resolved?
