### ISSUE TITLE
[V4] I need a docker image for my Gitlab builds that has Az function tools and Az cli for pulishing

### ISSUE THREAD

**Issue by aligneddev** [Azure/azure-functions-docker#860]
I've been struggling with this yesterday and today. I haven't done a lot of Docker work in the past.
We updated our az function from .Net 6 to .Net 7 isolated. Our function didn't start in Azure, we kept getting log messages "0 functions loaded" after `az functionapp deployment source config-zip --resource-group="$FUNCTION_GROUP" --name="$FUNCTION_NAME" --src="$OUTPUT/$ARTIFACT";`. I did change the settings in the Azure portal for version and .Net .

We found that it works after a Visual Studio publish and then we found [docs](https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-cli-csharp?tabs=azure-cli%2Cisolated-process#deploy-the-function-project-to-azure) pointing to ` func azure functionapp publish myfunction-test`.

Our existing build docker image for the pipeline has `FROM mcr.microsoft.com/azure-cli`. So I decided that it shouldn't be hard to build a dockerfile and image. I was wrong.

I've tried many permutations and can get a docker container built, 

Here's my latest error

Here's my dockerfile
```
# Contains az cli, azure function tools cli and dotnet-sdk-6.0
# this is 2.4 GB so it could be optimized in the future
# Created for ICCForwarder after the Azure function was updated to .Net 7

# FROM ubuntu:22.04
# sdk is  Debian GNU/Linux 11 (bullseye), 11, bullseye
FROM mcr.microsoft.com/dotnet/sdk:7.0
RUN apt update
# RUN apt update && apt install -y dotnet6
RUN apt install -y zip unzip
# https://stackoverflow.com/questions/65520596/deploy-azure-function-with-an-alpine-unhandled-error-event

# Install az cli and func ap cli
# .Net 7+ Azure Functions require isolated and the seperate func cli tools: 
# see https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-cli-csharp?tabs=azure-cli%2Cisolated-process#deploy-the-function-project-to-azure
RUN apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg
RUN curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg
RUN AZ_REPO=$(lsb_release -cs) && \
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list
RUN apt install -y azure-cli

# for bullseye
RUN echo "deb [arch=amd64] https://packages.microsoft.com/debian/$(lsb_release -rs | cut -d'.' -f 1)/prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list
## for Ubuntu: echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$AZ_REPO-prod $AZ_REPO main" | tee /etc/apt/sources.list.d/dotnetdev.list
RUN apt-get update && apt-get install -y azure-functions-core-tools-4
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
```

Is there a published image that I missed or that could be made? What guidance do you have for me?

My image fails when I try to run 
`az functionapp start --resource-group="$FUNCTION_GROUP" --name="$FUNCTION_NAME" --slot=stage;`
with 
```
/opt/az/lib/python3.10/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
ERROR: (InvalidApiVersionParameter) The api-version '2022-03-01' is invalid. The supported versions are '2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
Code: InvalidApiVersionParameter
```
that error was fixed on March 8, 2023 after the azure-cli released 2.46.0.

Here's a new error I get
```
$ az functionapp start --resource-group="$FUNCTION_GROUP" --name="$FUNCTION_NAME" --slot=stage;
ERROR: CLIInternalError: The command failed with an unexpected error. Here is the traceback:
ERROR: cannot import name 'DefaultErrorResponseException' from 'azure.mgmt.web.models' (/usr/lib/python3/dist-packages/azure/mgmt/web/models.py)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 558, in execute
    self.commands_loader.load_arguments(command)
```

so I still have something wrong with that image

**Comment by CooperLink** [comment]
Thank you for filing.  I am sorry but, this is not the intended usage of this issue tab.  For support with a production application and updating to the latest available version please create an incident so that our Customer Support Engineering staff can investigate the issue you are encountering. If you would like to create a custom container that includes AzureCLI as well as the host runtime. My best advice would be to copy all of the dependencies in the existing cli images.
