### ISSUE TITLE
Running issues in OpenShift cluster

### ISSUE THREAD

**Issue by agi1clj** [Azure/azure-functions-docker#864]
Hello,

I have the following Dockerfile:

```
FROM mcr.microsoft.com/azure-functions/node:4-nightly-node16-slim
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true
COPY ./dist /home/site/wwwroot
EXPOSE 80
```

I started the azure function on the local machine which is working:

![image](https://user-images.githubusercontent.com/38486343/224057928-81b2525b-4e5e-4aff-9a82-c59e27a39864.png)

But when I deployed it into an OpenShift cluster:

![image](https://user-images.githubusercontent.com/38486343/224058736-7e778b11-3a4d-4bf7-bbc3-917217a1c894.png)

It entered into DrainMode instead of production - without any changes.

I exposed the service on the openshift cluster with a route but the Azure Function is not reachable.

![image](https://user-images.githubusercontent.com/38486343/224058555-5d6216a3-3f73-4462-b7f3-3ebb3bb9faf0.png)

The Pod is running and there is no concrete error.. also the function was successfully mapped.

How I can set it to not enter into DrainMode and remain in Production?

**Comment by agi1clj** [comment]
Was a mistake into configuration for openshift.

**Comment by prestonr83** [comment]
What was the problem? I am running into same issue.
