### ISSUE TITLE
Provide Node.js 10 worker runtime

### ISSUE THREAD

**Issue by maxmalov** [Azure/azure-functions-docker#88]
The docs on docker hub say that `azure-functions/node:2.0` has node 10 worker runtime 
![image](https://user-images.githubusercontent.com/284129/54629010-de852000-4aa0-11e9-850c-0bbbbaa766f0.png)
but it is node 8 actually according to the docker file https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/stretch/amd64/node.Dockerfile#L8

**Comment by lhuk-futurice** [comment]
Agreed. Need this. Opened PR #116 for this.

**Comment by horihiro** [comment]
According to [this](https://nodejs.org/en/about/releases/), Node8 is already Maintenance LTS since2019-01-01, not Active LTS.
I hope that the PR #116 is merged as soon as possible.

**Comment by ahmelsayed** [comment]
This was added in #142 
There are 3 images/Dockerfiles now, [`node8.Dockerfile`](https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/stretch/amd64/node8.Dockerfile), [`node10.Dockerfile`](https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/stretch/amd64/node10.Dockerfile), [`node12.Dockerfile`](https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/stretch/amd64/node12.Dockerfile)

Current available tags are:

The image is: `mcr.microsoft.com/azure-functions/node`

Current available tags are:

* [`2.0`, `2.0.12733`, `2.0.12733-node8`](https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/stretch/amd64/node8.Dockerfile)
* [`2.0-appservice`, `2.0.12733-appservice`, `2.0.12733-node8-appservice`](https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/stretch/amd64/appservice/node8.Dockerfile)
* [`2.0-node10`, `2.0.12733-node10`](https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/stretch/amd64/node10.Dockerfile)
* [`2.0-node10-appservice`, `2.0.12733-node10-appservice`](https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/stretch/amd64/appservice/node10.Dockerfile)
* [`2.0-node12`, `2.0.12733-node12`](https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/stretch/amd64/node12.Dockerfile)
* [`2.0-node12-appservice`, `2.0.12733-node12-appservice`](https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/stretch/amd64/appservice/node12.Dockerfile)

This script [`build/node.sh`](https://github.com/Azure/azure-functions-docker/blob/master/build/node.sh) builds all the tags.
