### ISSUE TITLE
JVM Update Request for  Azure Functions for Java Container Image

### ISSUE THREAD

**Issue by yoshioterada** [Azure/azure-functions-docker#899]
According to the following information, the new version of AKS uses cgroup v2, 
and it is recommended to use Java version 11.0.16 or later in this environment.

https://github.com/Azure/AKS/releases
> Java/JDK support for cgroups v2 is available in JDK 11 (patch 11.0.16 and later) or JDK 15 and above. AKS Kubernetes 1.25+ uses cgroups v2. Please migrate your workloads to the new JDK.

However, the current Docker image for Azure Functions for Java utilizes Java 11.0.14.1, 
which may potentially cause problems when running on the new AKS environment.

```bash
> docker pull mcr.microsoft.com/azure-functions/java:4-java11
> docker exec -it 18f21a0287b4 /bin/sh
# ./usr/lib/jvm/msft-11-x64/bin/java -version
openjdk version "11.0.14.1" 2022-02-08 LTS
OpenJDK Runtime Environment Microsoft-31205 (build 11.0.14.1+1-LTS)
OpenJDK 64-Bit Server VM Microsoft-31205 (build 11.0.14.1+1-LTS, mixed mode)
```

So could you update the Java version to the latest release as soon as possible.

Thank you very much for your assistance and cooperation.

**Comment by yoshioterada** [comment]
I created following PR for this.

https://github.com/Azure/azure-functions-docker/pull/900

**Comment by vijaykumar911** [comment]
Hi  @yoshioterada  will update you soon

**Comment by vijaykumar911** [comment]
To update the Java version in your Azure Functions Docker image, you will need to create a new Docker image with the desired Java version.
Create a new file like Dockerfile in a directory on your local machine.In the Dockerfile, specify a base image that includes the Java version you want. For example, you can use the adoptopenjdk base image with the desired Java version.
.Once you have the updated Docker image available in a registry, you can update your AKS deployment to use the new image. You can modify the deployment manifest or Helm chart, depending on how you deploy your Azure Functions on AKS.

**Comment by yoshioterada** [comment]
@vijaykumar911  san 

Thank you so much for your feedback.
Yes, So I created a new PR as #900 

So please review it and please merge it to official image?

**Comment by yoshioterada** [comment]
I will close this issue.
Because today It was merged as follows.

https://github.com/Azure/azure-functions-docker/pull/900
https://github.com/Azure/azure-functions-docker/pull/902
