### ISSUE TITLE
Add arm32v7 builds for Azure Functions (Isolated)

### ISSUE THREAD

**Issue by andrewbuckingham** [Azure/azure-functions-docker#934]
Looking to run Azure Functions on a Raspberry Pi, Docker platform linux/arm/v7

The dotnet sdk has a build for this architecture and platform, but Azure Functions (Isolated) does not. Please could we have this?

**Comment by mohsinonxrm** [comment]
@andrewbuckingham , if you have RPI 4 (arm64/v8) then you can try the following: As-is, no support etc. and don't use in production.

https://hub.docker.com/r/mohsinonxrm/azure-functions-dotnet/tags

**Comment by CooperLink** [comment]
We currently have no plans to support this architecture.
