### ISSUE TITLE
None of the "4-node20" images are available in MCR

### ISSUE THREAD

**Issue by mikaello** [Azure/azure-functions-docker#983]
In https://github.com/Azure/azure-functions-docker/pull/912 it was added support for Node 20 images, namely:

| Tags | OS version |
| -|-|
| `4-node20` | Debian 11 |
| `4-node20-slim` | Debian 11 |
| `4-node20-appservice` | Debian 11 |
| `4-node20-core-tools` | Debian 11 |

But none of these are available at https://mcr.microsoft.com/en-us/product/azure-functions/node/about , the latest Node version is 18, causing it impossible to pull Node 20 images:

```
$ docker pull mcr.microsoft.com/azure-functions/node:4-node20-core-tools
Error response from daemon: manifest for mcr.microsoft.com/azure-functions/node:4-node20-core-tools not found: manifest unknown: manifest tagged by "4-node20-core-tools" is not found
```

**Comment by Bv-Lucas** [comment]
Agreed, until then I build my own, if anyone is interested I use the slim as source and my dockerfile is the following : 

```
FROM mcr.microsoft.com/azure-functions/node:4-node20-slim

RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash && \
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg && \
    mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg && \
    sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/debian/$(lsb_release -rs | cut -d'.' -f 1)/prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list' && \
    apt-get update && \
    apt-get install azure-functions-core-tools-4
```

**Comment by gpa** [comment]
Any updates?

**Comment by vivekjilla** [comment]
node20 images are available now at https://mcr.microsoft.com/en-us/product/azure-functions/node/about
